### ISSUE TITLE
Book suggestions

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#101]
# Books for book club

## Business-related:

1. [Noise](https://readnoise.com)
> show how noise helps produce errors in many fields, including medicine, law, public health, economic forecasting, food safety, forensic science, bail verdicts, child protection, strategy, performance reviews and personnel selection. And although noise can be found wherever people make judgments and decisions, individuals and organizations alike commonly ignore to its role in their judgments and in their actions. They show “noise neglect.” With a few simple remedies, people can reduce both noise and bias, and so make far better decisions.

2. [The Art of Leadership: Small Things, Done Well](https://www.amazon.com/Art-Leadership-Small-Things-Done-ebook-dp-B088KV4P6T/dp/B088KV4P6T) by Michael Lopp
> Many people think leadership is a higher calling that resides exclusively with a select few who practice and preach big, complex leadership philosophies. But as this practical book reveals, what's most important for leadership is principled consistency. Time and again, small things done well build trust and respect within a team.

3. [The Culture Map: Breaking Through the Invisible Boundaries of Global Business](https://www.amazon.com/Culture-Map-Breaking-Invisible-Boundaries/dp/1610392507)
Whether you work in a home office or abroad, business success in our ever more globalized and virtual world requires the skills to navigate through cultural differences and decode cultures foreign to your own....where people from starkly different backgrounds are expected to work harmoniously together.

4. [The Essential Deming](https://www.amazon.com/dp/B00AK8FCEG/) by W. Edwards Deming
> Leadership Principles from the Father of Quality. It's a set of articles, essays, and notes on management and quality control.

5. [Conscious Business](https://www.amazon.com/Conscious-Business-Build-Through-Values-ebook/dp/B0034184XM) by Fred Kofman
> ...fosters personal fulfillment in the individuals, mutual respect in the community, and success in the organization

6. [Getting to Yes](https://www.amazon.com/Getting-Yes-Negotiating-Agreement-Without-ebook/dp/B0051SDM5Q) by Roger Fisher
> ...offers a proven, step-by-step strategy for coming to mutually acceptable agreements in every sort of conflict.

7. [Powers of Two](https://www.amazon.com/Powers-Two-Relationships-Drive-Creativity-ebook/dp/B00E9FYT0O) by Joshua Wolf Shenk
> ...draws on neuroscience, social psychology, and cultural history to present the social foundations of creativity, with the pair as its primary embodiment.

8. [The Culture Code](https://www.amazon.com/Culture-Code-Secrets-Highly-Successful-ebook/dp/B01MSY1Y6Z/) by Daniel Coyle
> Where does great culture come from? How do you build and sustain it in your group, or strengthen a culture that needs fixing?

9. [Leadership & Self-deception: Getting out of the box](https://www.amazon.com/Leadership-Self-Deception-Getting-Out-Box/dp/1523097809) by The Arbinger Institute
> Leadership and Self-Deception uses an entertaining story everyone can relate to about a man facing challenges at work and at home to expose the fascinating ways that we blind ourselves to our true motivations and unwittingly sabotage the effectiveness of our own efforts to achieve happiness and increase happiness. We trap ourselves in a "box" of endless self-justification. Most importantly, the book shows us the way out.

10. [The First 90 Days: Proven Strategies for Getting Up to Speed Faster and Smarter](https://www.amazon.com/First-90-Days-Strategies-Expanded/dp/1422188612) by Michael D. Watkins
> proven strategies for conquering the challenges of transitions—no matter where you are in your career.

11. [The Checklist Manifesto: How To Get Things Right](https://www.amazon.com/Checklist-Manifesto-How-Things-Right-ebook/dp/B0030V0PEW/)
> "The Checklist Manifesto," which explains how a short, straightforward medical checklist can greatly reduce the chances of failure in life-or-death situations (and some less serious ones, for that matter). Himself a surgeon, Gawande argues that the medical field has, in some ways, become too sophisticated for its own good. "The volume and complexity of what we know has exceeded our individual ability to deliver its benefits correctly, safely, or reliably," he writes. "Knowledge has both saved us and burdened us."...Curious whether this approach could work in medicine, Gawande hunted for situations where checklists were used in his own field. Even skeptical readers will find the evidence staggering. Gawande found a host of studies that show dramatic drops in death or infection from a certain procedure once a hospital implemented a checklist for doing it right. Marshaling anecdotes and analysis, he implores the medical community to use checklists more widely. He also makes the case for rethinking teamwork and leadership in hospitals.

## Social

12. [Farmers or Hunter-Gatherers? The Dark Emu Debate](https://en.wikipedia.org/wiki/Farmers_or_Hunter-Gatherers%3F_The_Dark_Emu_Debate)
 
> Non-fiction book published this year, and written as a response to Bruce Pascoe's highly successful 2014 non-fiction book Dark Emu: Black Seeds: Agriculture or Accident? which describes evidence of agricultural and engineering activities by some Indigenous Australian groups, and suggests a more sedentary lifestyle than the more orthodox assessment that they were purely hunter-gatherers.[2] Sutton and Walshe reject Pascoe's thesis of Indigenous agriculture, and argue that his book contains serious errors and omissions.

13. [Between the World and Me](https://www.amazon.com/Between-World-Me-Ta-Nehisi-Coates/dp/1925240703) by Ta-Nehisi Coates

  Author's journey, personal tragedies, and what it means to be black in America

14. [Antifragile: Things That Gain From Disorder](https://www.amazon.com.au/Antifragile-Things-that-Gain-Disorder/dp/0141038225/)
> The book spans innovation by trial and error, life decisions, politics, urban planning, war, personal finance, economic systems, and medicine. And throughout, in addition to the street wisdom of Fat Tony of Brooklyn, the voices and recipes of ancient wisdom, from Roman, Greek, Semitic, and medieval sources, are loud and clear. Antifragile is a blueprint for living in a Black Swan world.

15. [Australia's second chance](https://www.readings.com.au/products/23737378/australias-second-chance-what-our-history-tells-us-about-our-future): What our history tells us about our future

## Money-related
16. [Financial Intelligence, Revised Edition: A Manager's Guide to Knowing What the Numbers Really Mean](https://www.amazon.com/Financial-Intelligence-Revised-Managers-Knowing/dp/1422144119) by Karen Berman and Joe Knight
> teach the basics of finance to managers who need to use financial data to drive their business. It also addresses issues that have become even more important in recent years--including questions around the financial crisis and those around broader financial and accounting literacy.

## Design-related
17. [Design for Cognitive Bias](https://abookapart.com/products/design-for-cognitive-bias) by David Dylan Thomas - Available August 2020

> We humans are messy, illogical creatures who like to imagine we’re in control—but we blithely let our biases lead us astray. In Design for Cognitive Bias, David Dylan Thomas lays bare the irrational forces that shape our everyday decisions and, inevitably, inform the experiences we craft. Once we grasp the logic powering these forces, we stand a fighting chance of confronting them, tempering them, and even harnessing them for good. Come along on a whirlwind tour of the cognitive biases that encroach on our lives and our work, and learn to start designing more consciously.

18. [Disability Visibility](https://www.penguinrandomhouse.com/books/617802/disability-visibility-by-alice-wong/)

> One in five people in the United States lives with a disability. Some disabilities are visible, others less apparent—but all are underrepresented in media and popular culture. Now, just in time for the thirtieth anniversary of the Americans with Disabilities Act, activist Alice Wong brings together this urgent, galvanizing collection of contemporary essays by disabled people.

## Self exploration/learning:

19. [The daily stoic](https://dailystoic.com) 366 Meditations on Wisdom, Perseverance, and the Art of Living
> The Daily Stoic offers 366 days of Stoic insights and exercises, featuring all-new translations from the Emperor Marcus Aurelius, the playwright Seneca, or slave-turned-philosopher Epictetus, as well as lesser-known luminaries like Zeno, Cleanthes, and Musonius Rufus. Every day of the year you'll find one of their pithy, powerful quotations, as well as historical anecdotes, provocative commentary, and a helpful glossary of Greek terms. 

20. [A Mind for Numbers](https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra-ebook/dp/B00G3L19ZU/) by by Barbara Oakley
> The learning strategies in this book apply not only to math and science, but to any subject in which we struggle. We all have what it takes to excel in areas that don't seem to come naturally to us at first, and learning them does not have to be as painful as we might think!

21. [Mindset](https://mindsetonline.com/) by Carol S Dweck
> Teaching a growth mindset creates motivation and productivity in the worlds of business, education, and sports.

22. [Make It Stick: The Science of Successful Learning](https://www.amazon.com/Make-Stick-Science-Successful-Learning/dp/B00M1Z2THY/)
> Make It Stick turns fashionable ideas like these on their head. Many common study habits and practice routines turn out to be counterproductive. Underlining and highlighting, rereading, cramming, and single-minded repetition of new skills create the illusion of mastery, but gains fade quickly. More complex and learning come from self-testing, introducing certain difficulties in practice, waiting to re-study new material until a little forgetting has set in, and interleaving the practice of one skill or topic with another. Speaking most urgently to students, teachers, trainers, and athletes, Make It Stick will appeal to all those interested in the challenge of lifelong learning and self-improvement.

23. [Quiet](https://www.quietrev.com/) by Susan Cain
> Unlocking the power of introverts

24. [The War of Art](https://www.amazon.com/War-Art-Steven-Pressfield-ebook/dp/B007A4SDCG) by Steven Pressfield
> ...aims to help readers channel creative energy, unlock potential and overcome the fears that stop us from reaching our fullest potential.

## Programming-related:

25. [Making Software](http://shop.oreilly.com/product/9780596808303.do)
> Many claims are made about how certain tools, technologies, and practices improve software development. But which claims are verifiable, and which are merely wishful thinking? Essays that discuss topics such as: are some programmers really ten times more productive than others? Does writing tests first help you develop better code faster? Can code metrics predict the number of bugs in a piece of software? Do design patterns actually make better software? What effect does personality have on pair programming? What matters more: how far apart people are geographically, or how far apart they are in the org chart?

26. [Ruby under a microscope](http://patshaughnessy.net/ruby-under-a-microscope) by Pat Shaughnessy
> Ruby Under a Microscope will guide you through the internals of some of Ruby's most-used facets. Using experimentation, theory, and two truckloads of diagrams, you'll clearly see how Ruby is implemented.

27. [Growing Object-Oriented Software Guided by Tests](https://www.amazon.com/Growing-Object-Oriented-Software-Addison-Wesley-Signature-ebook/dp/B002TIOYVW) by Steve Freeman and Nat Pryce
> ...describe the processes they use, the design principles they strive to achieve, and some of the tools that help them get the job done.

28. [Working Effectively with Legacy Code](https://www.amazon.com/Working-Effectively-Legacy-Code-EFFECT-ebook/dp/B005OYHF0A) by Michael Feathers
> ...offers start-to-finish strategies for working more effectively with large, untested legacy code bases.

29. [Clean Architecture](https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure-ebook/dp/B075LRM681) by Bob Martin
By applying universal rules of software architecture, you can dramatically improve developer productivity throughout the life of any software system.

30. [A Philosophy of Software Design](https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout-ebook/dp/B07N1XLQ7D/) by John Ousterhout
> how to decompose complex software systems into modules (such as classes and methods) that can be implemented relatively independently.

31. [Test Driven Development: By Example](https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530) by Kent Beck

This is the "original" TDD book.

32. [A Seat at the Table](https://www.goodreads.com/book/show/34416720-a-seat-at-the-table)

> Agile, Lean, and DevOps approaches are radical game changers, providing a fundamentally different way to think about how IT fits into the enterprise, how IT leaders lead, and how IT can harness technology to accomplish the objectives of the enterprise.

33. [The Psychology of Computer Programming](https://www.amazon.com/dp/0932633420)

This landmark 1971 classic is reprinted with a new preface, chapter-by-chapter commentary, and straight-from-the-heart observations on topics that affect the professional life of programmers.

Long regarded as one of the first books to pioneer a people-oriented approach to computing, The Psychology of Computer Programming endures as a penetrating analysis of the intelligence, skill, teamwork, and problem-solving power of the computer programmer.

**Comment by elle** [comment]
https://www.goodreads.com/en/book/show/39996759-a-philosophy-of-software-design

**Comment by elle** [comment]
The Atlas of AI: Power, Politics, and the Planetary Costs of Artificial Intelligence
https://www.google.com.au/books/edition/The_Atlas_of_AI/XvEdEAAAQBAJ

**Comment by elle** [comment]
We Need to Talk About Money
https://www.google.com.au/books/edition/We_Need_to_Talk_About_Money/2ywAEAAAQBAJ?hl=en

> An extraordinarily candid personal account of the ups and downs wrought by money, We Need To Talk About Money is a vital exploration of stories and issues that will be familiar to most. This is a book about toxic workplaces and misogynist men, about getting payrises and getting evicted. About class and privilege and racism and beauty. About shame and pride, compulsion and fear.

> In unpicking the shroud of secrecy surrounding money – who has it, how they got it, and how it shapes our lives – this boldly honest account of one woman’s journey upturns countless social conventions, and uncovers some startling truths about our complex relationships with money in the process.

**Comment by sugendran** [comment]
Am part way through this book https://www.goodreads.com/book/show/54716655-kill-it-with-fire

It's a bit of an extended blog post, but there are lots of interesting topics and perspectives on legacy systems

**Comment by elle** [comment]
[Team Topologies](https://teamtopologies.com)
> Team Topologies is a clear, easy-to-follow approach to modern software delivery with an emphasis on optimizing team interactions for flow.

**Comment by elle** [comment]
[Good Strategy Bad Strategy: The Difference and Why It Matters](https://www.amazon.com/dp/B004J4WKEC)

> Good Strategy/Bad Strategy clarifies the muddled thinking underlying too many strategies and provides a clear way to create and implement a powerful action-oriented strategy for the real world.

**Comment by tomdalling** [comment]
[The Manager's Path: A Guide for Tech Leaders Navigating Growth and Change](https://www.goodreads.com/book/show/33369254-the-manager-s-path)

> Managing people is difficult wherever you work, but the tech industry as a whole is pretty bad at it. Tech companies in general lack the experience, tools, texts, and frameworks to do it well. And the handful of books that share tips and tricks of engineering management don't explain how to supervise employees in the face of growth and change.
>
> In this book, author Camille Fournier takes you through the stages of technical management, from mentoring interns to working with the senior staff. You'll get actionable advice for approaching various obstacles in your path, whether you re a new manager, a mentor, or a more experienced leader looking for fresh advice. Pick up this book and learn how to become a better manager and leader in your organization.

**Comment by elle** [comment]
[The Art of Gathering: How We Meet and Why It Matters](https://www.amazon.com/Art-Gathering-How-Meet-Matters/dp/1594634920)

Recommended by Anton - about creating hospitable spaces for gatherings and building a community

**Comment by nickspragg** [comment]
[Range: Why Generalists Triumph in a Specialized World](https://www.amazon.com.au/dp/0735214484/)

> Provocative, rigorous, and engrossing, Range makes a compelling case for actively cultivating inefficiency. Failing a test is the best way to learn. Frequent quitters end up with the most fulfilling careers. The most impactful inventors cross domains rather than deepening their knowledge in a single area. As experts silo themselves further while computers master more of the skills once reserved for highly focused humans, people who think broadly and embrace diverse experiences and perspectives will increasingly thrive.

**Comment by elle** [comment]
Closing in favour of: https://github.com/Blackmill/book-club/issues/153
