### ISSUE TITLE
Sand Talk: Feb 23rd

### ISSUE THREAD

**Issue by pat** [Blackmill/book-club#103]
Continuing on with Sand Talk by Tyson Yunkaporta.

Aiming to read/discuss:

* Lemonade for Headaches
* Duck Hunting is Everybody's Business

MC: @pat
Notes: @lachlanhardy

See you 12 pm Tuesday, Feb 23rd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
## Lemonade for headaches

The dietary advice is an example of directly applicable knowledge and it complies with our understanding of modern dietary advice except in the implication that animal fats are only source of healthy fats. Not sure if the author is suggesting that an Aboriginal diet cannot be vegetarian, but it seems strongly implied.

We've not heard of any restaurants claiming to serve 'Australian Indigneous cuisine' - although we all know several that make a big deal about using native ingredients. Not sure if he hears more about those than we do, if this is a straw man, or what.

We again discussed where this book is going. Something about the subtitle made us expect solutions and Yunkaporta is not going to give us those. He is, however, broadening our thinking, and exposing us to new perspectives and concerns.

## Duck Hunting Is Everybody's Business

Everyone was uncomfortable with violence as an answer to, well, anything pretty much. We didn't have a very nuanced conversation about that and ended up veering back into discussion about the previous chapter.

**Comment by pat** [comment]
My own notes in preparation for the session:

## Lemonade for Headaches

Discussions about health, differences due to heritage, and 'holistic' approaches.

* I found all of this interesting, though would appreciate some references.
* There is one link to Western science with the pheremones example - no idea how well-known/researched this is, though. Don't suppose anyone went searching for more?
  
Then onto food, the importance of true holistic thinking, thinking about what's in season, ensuring variety.

* Adjusting the concept of what are authentic First Nations meals. Mostly sounds pretty reasonable to me.
* Does anyone actively adjust their cooking/diets based on what's in season?

Extended analogy of the immune system using a natural ecosystem.

* Greatly appreciated the depth here - though given I don't have a medical science background, I am making assumptions on the accuracy!

Finally, the combination of the five ways of thinking, and using the hand to represent those ways and how they are connected.

* Expands further on the previous chapter, which summarised the five and provided labels for them.
* Like Lachlan's pointed out over the past fortnight, there really is a building from the early chapters.
* Are we starting to see something of the claim on the cover - how Indigenous Thinking can save the World? Maybe not quite so clear on the saving part, though there's certainly opinionated hints. Providing clarity on the Indigenous Thinking part, though, is definitely happening.

## Duck Hunting is Everybody's Business

Gender, relationships, violence. Some heavy stuff here.

* Appreciated the acknowledgement of the long history of non-binary, trans, intersex people in First Nations cultures.
* Having explicit womens business and mens business… the term equity is used late in the chapter, which I guess is useful in comparison to equality. i.e. (as I think I understand it) things should be fair (equity), but that doesn't mean they're the same (equality).
* Violence is a tough thing to sit with.
* "Creation started with a big bang, not a big hug: violence is part of the pattern. The damage of violence is minimised when it is distributed throughout a system rarther than centralised into the hands of a few powerful people and their minions."
* Keeping violence in public, witnessed, limited - I can appreciate this. Maybe this approach is healthy? I feel it's presented somewhat reasonably. I don't like that it's a given that violence *should* be part of some punishments.
* The interplay of violence, gender, colonialism - the discussion of this had a quite intersectional feminist vibe, which I can get behind.
