### ISSUE TITLE
Unlearn: Aug 24: Chapters 7 & 8

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#126]
We're continuing: Unlearn by Barry O'Reilly (Readings, Bookshop, Amazon).

Aiming to read:

Chapter 7
Chapter 8
MC: @lachlanhardy
Notes: @HashNotAdam

See you all at 12pm AEST, Aug 24th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by elle** [comment]
> Your company has 21st century internet-enabled business processes, mid-20th century management processes, all built atop 19th century management principles.
> -- Gary Hamel

- Knowledge workers are different to factory workers - and thus you need to use different leadership styles
- "Turn the ship around" he asked what his report would do, and then ok'ed it. this is a way to ensure people are still doing the right thing while giving them space - a way to build competence

> Leadership responsibility is to clarify the desired outcomes, not the individual’s actions.

- Toyota Kata is very similar to coaching questions to ask

### Dalio's six principles

- Trust in radical truth and radical transparency
- Cultivate meaningful work and meaningful relationships
- Create a culture in which it is okay to make mistakes
- Get and stay in sync
- Believability weight your decision making
- Recognize how to get beyond disagreements

**Comment by HashNotAdam** [comment]
# Discussion

*Out of respect for their wishes, the tiny (albeit assertive) voice in the back room will not be discussed in the following minutes.*

## Chapter 7

@mcgain: It was frustrating for the book to support moving on from traditional command-and-control structures given, up to this point, it has spoken about these structures as a way to achieve the desired outcomes.
@lachlanhardy: This goes to concerns about how earlier chapters have glossed over big changes requiring teams and has focused on actions of executives in isolation.

Most people in the group were unaware that the military moved away from command-and-control a long time ago.

@jomontanari: Has read [Turn The Ship Around](https://www.goodreads.com/book/show/16158601-turn-the-ship-around) and, while a good book, it's confronting to read that we should model companies on [Al-Qaeda](https://en.wikipedia.org/wiki/Al-Qaeda) by delegating to those who have the most context.
@alphie: One challenge with this approach can be ensuring consistent processes across teams give authority is delegated and autonomy is promoted. Disparate processes can create efficiency at a team level but inefficiency in the broader company.
@lachlanhardy: It's very hard to learn how to provide people or teams with that context so they can be autonomous.
@john.telfer: Communicating that message to staff can be quite complicated while also accepting that perfection is unlikely, 80% is enough.
@mcgain: The same problem can exist when managing juniors.

@lachlanhardy: The chapter starts with "the majority of managers have risen to their current positions based on their competency to know what to do, when to do it, and always having the answer or solution at hand rather than helping others discover the answers and solutions." This is an insightful framing of the traditional career ladder where you are promoted to manage a team-based upon your individual contribution. It's no wonder that managers' default is to tell people to do what they would have done. If people are not asked to collaborate before they are managers, then they are being forced to switch when they are promoted rather than coming in with developed skills.

@mcgain: At the start of the chapter, O'Reilly discussed sequestering the executives of IAG for 8 weeks—meaning they wouldn't be doing their normal jobs—and, at first, this was annoying because it felt like they must not be particularly valuable if you can remove them from their jobs. Maybe a better framing is that they are good enough leaders that they can go away and the business doesn't fall down without them.
@lachlanhardy: Hadn't thought about this perspective. This might be because it's implied the companies are lacking and need O'Reilly's support, however, maybe the companies asking for support are the ones that have identified they have flaws and are already on the way to correcting them. Bad leaders probably aren't asking for support.

@alphie: There are many reasons organisations might choose to maintain the status quo but one of those is avoiding conflict. If things are constantly changing, there is a lot of uncertainty which can make those who are not involved in the process uncomfortable.

## Chapter 8

@lachlanhardy: This chapter seemed to cherry-pick examples from people or organisations who are well known for offering poor experiences for staff. This runs counter to the idea that staff should be considered as customers. Examples include AWS and Elon Musk where Amazon and Tesla have well-publicised disputes with staff.
@mcgain:  "Constantly referencing sociopath leaders isn't going to promote good leadership"

@lachlanhardy: There was an article that said that Tesla factories don't have safety warnings because Musk doesn't like the colour yellow. [Citation needed]

@lachlanhardy: The story of the bank that has customer phones which are a direct line to the CEO seems suspicious.
@john.telfer: It's hard to believe that someone whose time is so precious that upper management can't speak to them makes themselves available for random discussions.
@matthewborden: And it's underpinned by the idea that everyone trusts that could call the CEO with their problems without repercussions.

Regarding Elon Musk announcing fees for leaving your Telsa at a public charge station after it is full after reading a Twitter complaint from a customer.
@alphie: That's someone making a decision with the least amount of context for that decision.
@elle: I love that Musk's approach means he is getting feedback from actual customers but not that action is being taken based on the opinion of a single person. Basecamp keeps track of requests from customers and looks for broader patterns in those requests.
@john.telfer: Customer-centred design is not about reacting to one complaint on Twitter.

**Comment by lachlanhardy** [comment]
@HashNotAdam As requested, a citation: https://nymag.com/intelligencer/2018/04/tesla-workers-getting-hurt-because-elon-musk-hates-yellow.html Whether we consider NY Mag's Intelligencer column to be a credible source is an entirely different matter :)
