### ISSUE TITLE
Make It Stick: Dec 14: Chapter 4

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#140]
Make it Stick by Brown, Roediger, and McDaniel ([Readings](https://www.readings.com.au/products/17781177/make-it-stick-the-science-of-successful-learning), [Bookshop](https://bookshop.org/books/make-it-stick-the-science-of-successful-learning/9780674729018), [Amazon](https://www.amazon.com/Make-Stick-Peter-C-Brown-ebook/dp/B00JQ3FN7M/)).

Aiming to read:

* Chapter 4

MC: @elle
Notes: @HashNotAdam

See you all at 5pm AEST, Dec 14th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by elle** [comment]
# 4: embrace difficulties

- Jump training is structured with small steps leading to bigger actions, notching difficulties. practice is interleaved and spaced

## How learning occurs

1. Encoding - brain converts our perceptions into chemical and electrical changes that form mental representations of the patterns we observed. This is called memory traces and is in short term memory
1. Consolidation - strengthening those mental representations for long term memory. "New learning is labile: its meaning is not fully formed and therefore is easily altered. In consolidation, the brain reorganizes and stabilizes the memory traces. This may occur over several hours or longer and involves deep processing of the new material, during which scientists believe that the brain replays or rehearses the learning, giving it meaning, filling in blank spots, and making connections to past experiences and to other knowledge already stored in long-term memory... sleep seems to help memory consolidation, but in any case, consolidation and transition of learning to long-term storage occurs over a period of time."
1. Retrieval - durable learning requires two things: encoding and consolidation. And then associate this knowledge with cues to be able to recall it when needed.

Example: tying ropes -> needs practice

## Extending learning

- Updating retrieval cues

> sleep seems to help memory consolidation, but in any case, consolidation and transition of learning to long-term storage occurs over a period of time.

- Alliteration - can be useful or stand in the way
- Context - unleashes memories
- Easier isn't better - need effortful retrieval to re-enforce our learnings
  - Spacing, interleaving, and mixing up practice -> seems slow and unproductive, but is better for performance and learning in the long run
  - Example California Polytechnic baseball team

## How effort helps
1. Reconsolidating memory - effort triggers deeper learning
1. Creating mental models - a form of deeply entrenched and highly efficient skills
1. Broadening mastery - new associations and use cases
1. Fostering conceptual learning - better for discrimination and induction skills
1. Improving versatility - having multiple possibilities improves response
1. Priming the mind for learning - when we struggle with a problem rather being provided the solution

## More about learning strategies

1. Generation

  > It is better to solve a problem than to memorize a solution. It’s better to attempt a solution and supply the incorrect answer than not to make the attempt.
 
2. Reflection

  > The act of taking a few minutes to review what has been learned from an experience (or in a recent class) and asking yourself questions is known as reflection.
 - Write to learn

## Failure and the myth of errorless learning

> A fear of failure can poison learning by creating aversions to the kinds of experimentation and risk taking that characterize striving, or by diminishing performance under pressure, as in a test setting.

--
> The results support the finding that difficulty can create feelings of incompetence that engender anxiety, which in turn disrupts learning, and that “students do better when given room to struggle with difficulty.”

- Failure is the source of inspiration (Thomas Edison)
- Resilience underlies successful innovation
- Being able to fail liberates us to try different approaches

## Generative learning
- Generating the answer rather then being given the answer
- Blundering
  - https://css-tricks.com/learning-to-learn/

  > No one in the group knew this, and it was the first time I realized that all those silly playful things I was building were actually educating me; that I knew practical, real-life edge cases even though I hadn’t sought them out in a formal manner. I was so excited! I didn’t plan to become an SVG expert — it snuck up on me as I enjoyed myself, building things to relieve stress and play
  
  - Bonnie the gardener and learning latin plant names

## Undesirable difficulties

You can't learn when you drown. Three states: comfortable, learning zone, panic

> To be desirable, a difficulty must be something learners can overcome through increased effort.

## Takeaways
Learning is at least a three-step process:

1. Initial encoding of information is held in short-term working memory before being consolidated into a cohesive representation of knowledge in long-term memory.
1. Consolidation reorganizes and stabilizes memory traces, gives them meaning, and makes connections to past experiences and to other knowledge already stored in long-term memory.
1. Retrieval updates learning and enables you to apply it when you need it. 

Learning always builds on a store of prior knowledge. We interpret and remember events by building connections to what we already know.

Long-term memory capacity is virtually limitless: the more you know, the more possible connections you have for adding new knowledge.

Our ability to recall knowledge depends on repeated use of the information.

Retrieval practice that is difficult and effortful is better - makes pliable knowledge more solid. Reconsolidating helps connect memories with new information and recent learning.

Practice that is interleaved and varied -> increases ability of discrimination, induction, and versatility of use later.

Trying to come up with the answer is better!

**Comment by HashNotAdam** [comment]
Sorry, both my discussion notes and also the audio recording were lost when I moved computers 😭
