### ISSUE TITLE
The art of gathering: March 15: chapter 3

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#148]
Book: The art of gathering, how we meet and why it matters by Priya Parker ([Readings](https://www.readings.com.au/products/26567315/the-art-of-gathering-how-we-meet-and-why-it-matters), [BookShop](https://bookshop.org/books/the-art-of-gathering-how-we-meet-and-why-it-matters/9781594634932), [Amazon](https://www.amazon.com/Art-Gathering-How-Meet-Matters-ebook/dp/B07637KVXL))

Aiming to read:
- Chapter 3: don't be a chill host

MC: @mcgain 
Notes: @sugendran 

See you all at 12pm AEST, March 15th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by sugendran** [comment]
== Chapter 3 ==

- Most of us are chill hosts
	- people who are catering are not as chill.. there is a run sheet for the night based on catering
	- groups of 6 or more, thought put into the group dynamic when inviting
	- 

- discussion around phones at the party...
	- host controlling the phone to prevent people from vanishing into their phone to not participate
		- can force people to participate more
	- depends on the situation..
		- sometimes you want people to comfortable enough to zone out...
- being present in meetings..
	- do not disturb can alleviate the noise
	- Is this a host responsibility?
		- maybe people are adults and they should practice good meeting hygine
- When you're in a group, the group is above your personal interests
	- if everyone focuses only their personal interests then the group wont work

- What is generous authority
	- Tell them what to do (authority), but focus on their interests (generous)
	- Exercise your authority but focus on the needs of the group members
	- How does this work, if everyone is there for a different purpose? How is this generous?
	- What if you leave it unstructured? To see what happens?
		- Sometimes the unexpected happens, sometimes that is great
 
- Is the Australian cultural expectation of a gathering different to the authors?
	- Do we have some bias against a host being the one that is there to entertain the guests?
	- People helping at dinners? Not everyone is onboard with helping, or being helped...
		- having a minor backlog can give the guests something to participate in

- Ungenerous authority... 
	- using authority that you don't actually have
		- example: "listen to me, i'm paying for your beer"

- The event is not for the host to decide.. it has to fit the archetype

**Comment by elle** [comment]
Thanks @sugendran!
