### ISSUE TITLE
 The art of gathering: March 29: Chapter 5

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#150]
Book: The art of gathering, how we meet and why it matters by Priya Parker ([Readings](https://www.readings.com.au/products/26567315/the-art-of-gathering-how-we-meet-and-why-it-matters), [BookShop](https://bookshop.org/books/the-art-of-gathering-how-we-meet-and-why-it-matters/9781594634932), [Amazon](https://www.amazon.com/Art-Gathering-How-Meet-Matters-ebook/dp/B07637KVXL))

Aiming to read: 

    Chapter 5:  Never start a funeral with logistics 

MC: @antulik
Notes: @pat

See you all at 12pm AEST, March 29th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by pat** [comment]
MC: @antulik

**Comment by pat** [comment]
- Several people didn't finish the chapter, found it a bit boring.

### Priming

- example is having an agenda to meetings.
- Useful thinking about workshops, and start to ask some questions a day before.
- considered within dating, starting some conversation via messages before an in-person date can help build excitement.
- Rails Camp does a little bit of priming now, but initially had a lot more around preparing talks, hack projects. Hype had happened on Twitter, doesn't occur as much now.
- Could use Slack, though does it become more an extension of the conference vs priming? Giving a space for people to discuss isn't necessarily priming, but seeding conversation about certain topics on Slack would be priming.
- Flash cards for learning attendee names/faces.
- Asking people what they want to discuss at a conference, put it on a badge - is that priming? If it's explained why you're asking for them.
- Naming/priming is all part of communicating clearly, which is a common thread in all the chapters.
- Badges aren't always embraced, is priming of the purpose of such tools necessary?
    - Put first name large, and on both sides!
- Could list attendees at an event, but that doesn't scale. Privacy implications as well.
- Invitations to events as a form of priming, and explaining why the invite has been made.
- Onboarding as priming.
- How can we be better at priming? Consider purpose of organisers, attendees. Send emails ahead of time, build excitement.
    - Blackmill workshops have a meet-the-host one-on-one chat prior to the workshop itself. Helps to build rapport and trust, and to cater content to people's needs.
    - Being upfront about interview processes, timing, etc.
    - Duration as a way of managing expectations.
    - Appreciating the reminder of priming, as we don't always have it in mind, or don't treat it as important.
- People are uncomfortable with the idea of being kidnapped for an event (or other unexpected activities)

### Ushering

- Example of Fat Duck restaurant, confusion -> relaxed, with setting expectations of something a bit more theatrical.
- Immersive theatre, entering through different paths, separate from your social group.
- Is changing realities actually worth it? Though, escaping from reality can be great!
- Theme park in Portland.
- Work meetings in distinct meeting rooms - moving into that space is a light form of ushering.
- Unboxing as a form of ushering, launch screens.
- When you're given a nametag at a conference, or finding which table you're sitting at for a wedding.

### Launching

- How to include a Welcome/Acknowledgement of Country while managing the vibe?
- Same with keynote speakers - hard to know how they'll affect the vibe.
- Challenge of community vs cliques, how to make sure all people feel welcome.
- Question about what's the purpose of welcomes to country.
