### ISSUE TITLE
New book options/suggestions

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#16]
Please post suggestions for the next book to read in the comments

We'd be starting it May 21st, I think

cc @HashNotAdam @nickspragg @lachlanhardy @cattekin @SophieRoseMcDonald @keithpitty @saramic @minty8880

**Comment by lachlanhardy** [comment]
Here's the books that have been suggested in the past:

1. [Conscious Business](https://www.amazon.com/Conscious-Business-Build-Through-Values-ebook/dp/B0034184XM): how to build value through values
1. [Understanding Computation](https://www.amazon.com/Understanding-Computation-Machines-Impossible-Programs-ebook/dp/B00CT3C4IM) by Tom Stuart
1. [Design patterns in Ruby](https://www.amazon.com/Design-Patterns-Reader-Addison-Wesley-Professional-ebook/dp/B004YW6M6G) by Russ Olsen
1. [Growing Object-Oriented Software Guided by Tests](https://www.amazon.com/Growing-Object-Oriented-Software-Addison-Wesley-Signature-ebook/dp/B002TIOYVW) - Nat Pryce
1. [Working effectively with legacy code](https://www.amazon.com/Working-Effectively-Legacy-Code-EFFECT-ebook/dp/B005OYHF0A)
1. [Clean Architecture](https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure-ebook/dp/B075LRM681) by Bob Martin
1. [Quiet revolution: unlocking the power of introverts](https://www.quietrev.com)

**Comment by elle** [comment]
Other ones on my list:
1. [Daring Greatly](https://www.amazon.com/Daring-Greatly-Courage-Vulnerable-Transforms-ebook/dp/B007P7HRS4/): How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead by Brene Brown
1. [How to measure anything](https://www.amazon.com/How-Measure-Anything-Intangibles-Business/dp/1118539273), finding the value of intangibles in business
1. [Primed to Perform](https://www.amazon.com/Primed-Perform-Performing-Cultures-Motivation-ebook/dp/B00S590OQI): How to Build the Highest Performing Cultures Through the Science of Total Motivation
1. [Getting to Yes](https://www.amazon.com/Getting-Yes-Negotiating-Agreement-Without-ebook/dp/B0051SDM5Q): Negotiating Agreement Without Giving In
1. [Powers of Two](https://www.amazon.com/Powers-Two-Relationships-Drive-Creativity-ebook/dp/B00E9FYT0O): How Relationships Drive Creativity

**Comment by lachlanhardy** [comment]
13. [Dare to Lead](https://www.amazon.com/dp/B07CWGFPS7/): Brave Work. Tough Conversations. Whole Hearts by Brené Brown
14. [The Essential Deming](https://www.amazon.com/dp/B00AK8FCEG/): Leadership Principles from the Father of Quality. It's a set of articles, essays, and notes by [W. Edwards Deming](https://en.wikipedia.org/wiki/W._Edwards_Deming).

**Comment by antoinemacia** [comment]
Hey everyone, would love to partake! Here are some more suggestions that's been on my list (though quiet furnished already!)

15. [The War of Art](https://www.amazon.com.au/War-Art-Steven-Pressfield-ebook/dp/B007A4SDCG): Break Through the Blocks and Win Your Inner Creative battles...
16. [A Philosophy of Software design](https://www.goodreads.com/book/show/39996759-a-philosophy-of-software-design)
17. [A Mind for Numbers](https://www.goodreads.com/book/show/18693655-a-mind-for-numbers): How to Excel at Math and Science (Even If You Flunked Algebra)

**Comment by elle** [comment]
Elle's top choices: 8, 9, 10, 13
Lachlan's top choices: 9, 14, 2

**Comment by nickspragg** [comment]
Nick's top choices: 7, 10, 13

**Comment by HashNotAdam** [comment]
7, 8, 10

**Comment by nickspragg** [comment]
18. [Resilient Management](https://abookapart.com/products/resilient-management) by Lara Hogan

**Comment by lachlanhardy** [comment]
Hi, @antoinemacia! Thanks for joining. I now really want to read your suggestion of A Mind For Numbers. 

@everyone
Looks like number 10 is the most commonly picked above, so I reckon we'll go with that.
https://www.amazon.com/Primed-Perform-Performing-Cultures-Motivation-ebook/dp/B00S590OQI

Seems like Part I is only 30 pages, so let's try to read that by next Tuesday. I'll raise an issue now.

**Comment by lachlanhardy** [comment]
Adding for next time: [An Elegant Puzzle](https://www.amazon.com/dp/B07QYCHJ7V/)
