### ISSUE TITLE
NOV 15: Team Topologies: Chapter 5 - The Four Fundamental Team Topologies

### ISSUE THREAD

**Issue by kunzmann** [Blackmill/book-club#169]
Book: Team Topologies: Organizing business and technology teams for fast flow by Matthew Skelton and Manuel Pais.
Link: https://teamtopologies.com/

Aiming to read:

Chapter 5: The Four Fundamental Team Topologies
MC: @kunzmann
Notes: @sugendran

See you all at 12pm AEST, November 15th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by sugendran** [comment]
[chpt-5.pdf](https://github.com/Blackmill/book-club/files/10008516/chpt-5.pdf)
