### ISSUE TITLE
Inclusive design communities: Jan 24: intro and chapter 1

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#173]
Book: Inclusive Design Communities by Sameera Kapila.
Link: https://abookapart.com/products/inclusive-design-communities

Aiming to read:

- Foreword
- Intro
- Chapter 1: Understanding inclusion

MC: @nickspragg
Notes: @sugendran

See you all at 12pm AEST, Jan 24th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by sugendran** [comment]
# Intro:
 - Q: who's picking up the and is surprised by the fact that the intro is all about topics of inclusion
  - A: the person you're handing the book to.

# Chapter 1:

## Identity: 
  - Covers gender, age, race, socioeconomic status, sexual orientation, health, and more.
  - Book jumps into the topic very quickly and it doesn't take people on the journey, so people who need to read the book are going to find it very antagonistic. 
  - The allyship section has lots of good things and the not making it about yourself was great. Would have been great to have it at the start as well to help frame the conversation. The topics are all about creating a supportive environment for others.
  - Separate intent from impact
  - Sometimes there is a difference between support and activism. Most people are in support, not everyone is supports activism.
    - Does activism create friction and tension in the workplace?
    - When we feel uncomfortable about conversations, why is it?
      - privilege ?
      - the topic itself ?
      - every conversation moves everyone forward though
    - In some cases activism can be micro aggressions as the people you're allied with aren't looking for activism

## Marginalisation:
 - Describing people by their demographics unless you're trying to find someone in the crowd is a micro-aggression.
   - Why don't we describe people by skills? e.g. the meeting my friend Joe who is a frontend dev.
 - marginalised is a better phrase than minority
   - acknowledges they're an impacted group
   - creates empathy towards that group
 - Suggestion: read non-violent communication
 - Sometimes it's hard for people to call out the marginalisation
   - it's okay to also remove yourself from situations
 - When you ask for information, are you asking for something that people don't want to volunteer and it's not a question that is relevant for anything
 - Micro aggressions are not always the same for everyone, it's very situational

 ## Intent and Impact
  - "Assume everyone had good intent" 
    - Is this good advice? Sometimes people said things without good intent - maybe they're just racist
  - Genuine intent shows an interest in the well being of others, but does not always lead to impact
  - Intent is important but doesn't negate a negative impact
