### ISSUE TITLE
Thinking in Systems: July 19: Intro and chapter 1

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#192]
Thinking in Systems: A Primer, by Donella H. Meadows
Link: https://www.goodreads.com/book/show/3828902-thinking-in-systems

Aiming to read:
- Intro
- Chapter 1: The basics

MC: @elle
Notes: @HashNotAdam

See you all at 12pm AEST, July 19th @ https://blackmill.co/meet

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
# Thinking in Systems
by Meadows, Donella H.

## A Note from the Editor

continual growth in population and consumption could severely damage the ecosystems and social systems that support life on earth, and that a drive for limitless economic growth could eventually disrupt many local, regional, and global systems


Once you start to see the events of the day as parts of trends, and those trends as symptoms of underlying system structure, you will be able to consider new ways to manage and new ways to live in a world of complex systems.

## Introduction: The Systems Lens
> Managers are not confronted with problems that are independent of each other, but with dynamic situations that consist of complex systems of changing problems that interact with each other. I call such situations messes. â€¦ Managers do not solve problems, they manage messes.
> - Russell Ackoff, operations theorist

The system, to a large extent, causes its own behaviour! Stop casting blame, see the system as the source of its own problems, and find the courage and wisdom to restructure it.

Systems thinkers call these common structures that produce characteristic behaviours archetypes. When I first planned this book, I called them â€œ system traps. Then I added the words â€œ and opportunities, because these archetypes, which are responsible for some of the most intransigent and potentially dangerous problems, also can be transformed, with a little systems understanding, to produce much more desirable behaviours.

The behaviour of a system cannot be known just by knowing the elements of which the system is made

# Part One: System Structure and Behaviour

## 1: The Basics

**A system is an interconnected set of elements that is coherently organised in a way that achieves something.**

A system must consist of three kinds of things:

- elements,
- interconnections, and
- a function or purpose.

System is more than the sum of its parts. It may exhibit adaptive, dynamic, goal - seeking, self - preserving, and sometimes evolutionary behaviour.

Systems can be self-organising, and often are self-repairing over at least some range of disruptions. They are resilient, and many of them are evolutionary. Out of one system other completely new, never before imagined systems can arise.

**Look Beyond the Players to the Rules of the Game**

Elements do not have to be physical things. Intangibles are also elements of a system.

How to know whether you are looking at a system or just a bunch of stuff:

A. Can you identify parts ?
B. Do the parts affect each other?
C. Do the parts together produce an effect that is different from the effect of each part on its own?
D. Does the effect, the behaviour over time, persist in a variety of circumstances?

Many of the interconnections in systems operate through the flow of information. Information holds systems together and plays a great role in determining how they operate.

If information-based relationships are hard to see, functions or purposes are even harder. A system's function or purpose is not necessarily spoken, written, or expressed explicitly, except through the operation of the system. The best way to deduce the system's purpose is to watch for a while to see how the system behaves.

Purposes are deduced from behaviour, not from rhetoric or stated goals.

### Language
The word **function** is generally used for a nonhuman system, the word **purpose** for a human one, but the distinction is not absolute, since so many systems have both human and nonhuman elements.

An important function of almost every system is to ensure its own perpetuation.

Systems can be nested within systems. Therefore, there can be purposes within purposes.

Any of those sub-purposes could come into conflict with the overall purpose the student could cheat, the professor could ignore the students in order to publish papers, the administrator could balance the budget by firing professors.

Keeping sub-purposes and overall system purposes in harmony is an essential function of successful systems.

A change in purpose changes a system profoundly, even if every element and interconnection remains the same.

A stock is the foundation of any system. Stocks are the **elements of the system that you can see, feel, count, or measure at any given time**. A system stock is just what it sounds like : a store, a quantity, an accumulation of material or information that has built up over time. It may be the water in a bathtub, a population, the books in a bookstore, the wood in a tree, the money in a bank, your own self - confidence. A stock does not have to be physical. Your reserve of good will toward others or your supply of hope that the world can be better are both stocks.

Stocks change over time through the actions of a flow. Flows are filling and draining, births and deaths, purchases and sales, growth and decay, deposits and withdrawals, successes and failures. A stock, then, is the present memory of the history of changing flows within the system.

Figure 1. How to read stock and flow diagrams. In this book, stocks are shown as boxes, and flows as arrow - headed pipes leading into or out of the stocks. The small T on each flow signifies a faucet; it can be turned higher or lower, on or off. The clouds stand for wherever the flows come from and go to the sources and sinks that are being ignored for the purposes of the present discussion.

If you understand the dynamics of stocks and flows their behaviour over time you understand a good deal about the behaviour of complex systems.

Systems thinkers use graphs of system behaviour to understand trends over time, rather than focusing attention on individual events. We also use behaviour - over - time graphs to learn whether the system is approaching a goal or a limit, and if so, how quickly.

The horizontal axis of time allows you to ask questions about what came before, and what might happen next. It can help you focus on the time horizon appropriate to the question or problem you are investigating.

**Dynamic equilibrium** its level does not change, although water is continuously flowing through it.

All models, whether mental models or mathematical models, are simplifications of the real world. You know all the dynamic possibilities of this bathtub. From it you can deduce several important principles that extend to more complicated systems:

- As long as the sum of all inflows exceeds the sum of all outflows, the level of the stock will rise.
- As long as the sum of all outflows exceeds the sum of all inflows, the level of the stock will fall.
- If the sum of all outflows equals the sum of all inflows, the stock level will not change; it will be held in dynamic equilibrium at whatever level it happened to be when the two sets of flows became equal.

On top of that, **when we do focus on flows, we tend to focus on inflows more easily than on outflows**. Therefore, we sometimes miss seeing that we can fill a bathtub not only by increasing the inflow rate, but also by decreasing the outflow rate.

Similarly, a company can build up a larger workforce by more hiring, or it can do the same thing by reducing the rates of quitting and firing.

A stock takes time to change, because flows take time to flow.

Stocks generally change slowly, even when the flows into or out of them change suddenly. Therefore, stocks act as delays or buffers or shock absorbers in systems.

People often underestimate the inherent momentum of a stock. It takes a long time for populations to grow or stop growing, for wood to accumulate in a forest, for a reservoir to fill up, for a mine to be depleted.

Industrialisation cannot proceed faster than the rate at which factories and machines can be constructed and the rate at which human beings can be educated to run and maintain them. Forests can't grow overnight.

Once contaminants have accumulated in groundwater, they can be washed out only at the rate of groundwater turnover, which may take decades or even centuries.

The time lags that come from slowly changing stocks can cause problems in systems, but they also can be sources of stability.

The time lags imposed by stocks allow room to manoeuvre, to experiment, and to revise policies that aren't working.

### Concept of feedback

- Stocks allow inflows and outflows to be decoupled and to be independent and temporarily out of balance with each other.
- It isn't feasible to harvest a forest at the precise rate at which the trees are growing.
- Reservoirs enable residents and farmers downriver to live without constantly adjusting their lives and work to a river's varying flow, especially its droughts and floods.
- Banks enable you temporarily to earn money at a rate different from how you spend.
- Levels in stocks: If inventories rise too high, then prices are cut or advertising budgets are increased, so that sales will go up and inventories will fall.

Systems thinkers see the world as a collection of stocks along with the mechanisms for regulating the levels in the stocks by manipulating flows.

That means system thinkers see the world as a collection of â€œ feedback processes.

Everything we do as individuals, as an industry, or as a society is done in the context of an information - feedback system.

When a stock grows by leaps and bounds or declines swiftly or is held within a certain range no matter what else is going on around it, it is likely that there is a control mechanism at work.

### A feedback loop

You can imagine an outflow - adjusting feedback loop for spending.

**A feedback loop is a closed chain of causal connections from a stock, through a set of decisions or rules or physical laws or actions that are dependent on the level of the stock, and back again through a flow to change the stock.**

### Stabilising loops - Balancing feedback loops

A balancing feedback loop - Balancing feedback loops are goal - seeking or stability - seeking.

If you push a stock too far up, a balancing loop will try to pull it back down. If you shove it too far down, a balancing loop will try to bring it back up.

The function of this system is to bring the discrepancy between coffee's temperature and room's temperature to zero, no matter what the direction of the discrepancy.

Balancing feedback loops are equilibrating or goal - seeking structures in systems and are both sources of stability and sources of resistance to change.

The goal of the feedback loop may never be reached by the actual stock. But in the simple example of a cup of coffee, the drink eventually will reach room temperature.

### Runaway Loops - Reinforcing Feedback

Profits fell because investment fell, and investment fell because profits fell.

The second kind of feedback loop is amplifying, reinforcing, self-multiplying, snowballing, a vicious or virtuous circle that can cause healthy growth or runaway destruction. It is called a reinforcing feedback loop,

The more prices go up, the more wages have to go up if people are to maintain their standards of living. The more wages go up, the more prices have to go up to maintain profits. This means that wages have to go up again, so prices go up again.

The more soil is eroded from the land, the less plants are able to grow, so the fewer roots there are to hold the soil, so the more soil is eroded, so less plants can grow.

The more money you have in the bank, the more interest you earn, which is added to the money already in the bank, where it earns even more interest.

Depending on what is growing, money in the bank, people with HIV/AIDS, pests in a cornfield, a national economy, or weapons in an arms race.

Reinforcing feedback loops are self-enhancing, leading to exponential growth or to runaway collapses over time. They are found whenever a stock has the

try to think of any human decision that occurs without a feedback loop that is, a decision that is made without regard to any information about the level of the stock it influences.

### The rule of 72

The time it takes for an exponentially growing stock to double in size, the â€œ doubling time, equals approximately 70 divided by the growth rate (expressed as a percentage). Example: If you put $ 100 in the bank at 7% interest per year, you will double your money in 10 years ( 70 % 7 = 10 ). If you get only 5% interest, your money will take 14 years to double.

**Q: If A causes B, is it possible that B also causes A?**

You'll stop looking for who's to blame; instead you'll start asking, What's the system. The concept of feedback opens up the idea that a system can cause its own behaviour.

Of course, in real systems feedback loops rarely come singly. They are linked together, often in fantastically complex patterns. A single stock is likely to have several reinforcing and balancing loops of differing strengths pulling it in several directions.

Another terminology option:

- Positive feedback loops - spiralling
- Negative feedback loop - the more something happens, the less something else happens

**Comment by HashNotAdam** [comment]
First impressions of the book:
- Seems like it will be fun
- Strong correlation with the Hidden Brain podcast (mental health/dopamine balance / hedonic treadmill)
- Engaging, but requires some deeper thought  or revision to understand fully
- Using flows and interconnects was an interesting way to think about systems rather than as a machine

So far, a system has been explained as having inputs and outputs rather than a cyclical system that flows back into itself.

> A system is an interconnected set of elements that is coherently organized in a way that achieves something. If you look at that definition closely for a minute, you can see that a system must consist of three kinds of things: elements, interconnections, and a function or purpose.

What is a coherent organisation?
Can something be a system if it isn't coherently organized?

> see the system as the source of its own problems, and find the courage and wisdom to restructure it

Regarding people management, issues are rarely because of individuals; they are usually systemic.

The concept of systemic issues is presented in the book as new, but because the draft was developed in 1993, it is no longer groundbreaking.

As technologists, we are trained to think in systems early in our careers. Even if we haven't been doing it formally, most of us would be thinking this way implicitly.

When thinking about a system, we have a tendency to focus on how the inflow affects the system without considering the outflow

> Sand scattered on a road by happenstance is not, itself, a system.

What if the scattering was considered and intentional? What one person sees as a random distribution could be another person's art.

Every decision we make past infancy is based on some form of feedback, although the reasoning can occur subconsciously. Potentially, this is why a system is described as an "interconnected set of elements that is coherently organized in a way that achieves something"

> A stock is the foundation of any system. Stocks are the elements of the system that you can see, feel, count, or measure at any given time.

> Stocks change over time through the actions of a flow.

The concept of a change of stock is similar to how we train engineering teams to track metrics on an ongoing basis to see how they change over time.

Tickets coming in and being completed is an example of a system in an engineering team.

There is an idea that teams are immutable. Whenever any member changes, you have a new team. Whether you consider this to be a change in the system, however, would depend on the scope at which you are looking. When you view the change at the team level, while the individuals are elements, the way they communicate also informs the interconnections. On the other hand, if you are looking from a whole company level, each team is an element that is still performing the same task it used to and is still communicating to other elements with the same intent.

> The time it takes for an exponentially growing stock to double in size, the “doubling time,” equals approximately 70 divided by the growth rate (expressed as a percentage).

This is known as the Rule of 72

A nice way to refer to the difference between positive and negative feedback is reinforcing and redirecting feedback. This reframes the feedback within the context of either confirming that behaviour aligns with desires or expectations or supporting someone to adapt and meet expectations.
