### ISSUE TITLE
Let's talk culture: September 6: chapters 6–7

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#198]
Book: [Let's talk culture](https://shanemhatton.com/lets-talk-culture/) by Shane Michael Hatton

Aiming to read:
- Chapter 6: The clarification conversation
- Chapter 7: The communication conversation

MC: @Alysander
Notes: @HashNotAdam 

See you all at 12pm AEST, September 6th @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by Alysander** [comment]
Hello! This is my github

**Comment by HashNotAdam** [comment]
So all I needed to do was put an @ in front 😂

**Comment by Alysander** [comment]
@HashNotAdam since you were interstate let me know if you want to have a catch up call about this weeks material
