### ISSUE TITLE
July 2: Primed to Perform Chapters 10-11

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#22]
[Primed to Perform](https://www.amazon.com/Primed-Perform-Performing-Cultures-Motivation-ebook/dp/B00S590OQI)

Aiming to read:

- Chapter 10: The Playground
- Chapter 11: The Land of a Thousand Ladders

MC: @HashNotAdam 
Notes: @mcgain   

See you Tuesday in Zoom:

Join Zoom Meeting
https://zoom.us/j/914785529

Topic: Blackmill Book Club
Time: Jun 18, 2019 12:00 PM Canberra, Melbourne, Sydney
Every week on Tuesday. First one: Mar 26, 2019 12:00 PM

Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/914785529/ics?icsToken=5dd411172ce371e9770226b355c2f163863fe4efff5e00b09866a6b7be767b09

One tap mobile
+61871501149,,914785529# Australia
+61280152088,,914785529# Australia

Dial by your location
+61 8 7150 1149 Australia
+61 2 8015 2088 Australia
Meeting ID: 914 785 529
Find your local number: https://zoom.us/u/abWGuMO6GJ

**Comment by mcgain** [comment]
Notes added to main doc https://github.com/Blackmill/book-club/commit/b3647dd819e0e9f9223d9783d31ea96885861638
