### ISSUE TITLE
The Engineering Executive's Primer: July 17: chapters 7–8

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#225]
Book: [The Engineering Executive's Primer](https://lethain.com/eng-execs-primer/) by Will Larson

Aiming to read:

Chapters:
- 7: Participating in Mergers and Acquisitions
- 8: Developing Leadership Styles

MC: @mcgain 
Notes: @elle

See you all at 12pm AEDT, July 17 @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by mcgain** [comment]
## 7: Participating in Mergers and Acquisitions

After an acquisition, unlike most other departments, Engineering will be "intimately" involved with the acquired company, having to integrate and run it.

### Complex Incentives
* Miscommunication happens a lot in these processes.
* Beware the sunk cost fallacy once you've done six months of research into the aquisition

### Shared Perspective
You need three tools:
1. Business Strategy
2. Acquisition Thesis
3. Engineering Evaluation
Numbers 2 and 3 are often missing in a company (sometimes even 1), so you can get these started yourself

### Business Strategy
1. What are your business lines?
2. What are your revenue and cash flow expectations for those lines?
3. How does M&A fit into the above?
4. What kind of A? Acquihires? Products? Entire Businesses?
5. What kinds of M&A would you consider?

Common strategies include:
* Acquiring revenue or users for core business
* New business lines
* Innovating
* Reducing competition 

### Acquisition Thesis 
How does this acquisition fit into the above strategy?
Identify the assumptions needed for the acquisition to fit into the strategy
Pay attention to valuation. Venture capital can inflate valuations, but you cannot

### Engineering Evaluation
1. What evidence do you need to validate your thesis? 
2. Ask for evidence
3. Meet with someone to followup on missing detail
4. Interview people who will be senior, or for an acquihire, a bunch of people

Remember: Acquisitions are painful, and rarely succeed, so err on the side of annoying fewer people

Some things that should be on your template:
* Product Implementation
* IP
* Security
* Compliance
* Integration mismatches
* Costs and scalability
* Culture


### Integration Plan
* Run the business "as-is" for 6 months while consolidating technology where possible
* Merge the org chart
* Be direct and transparent

Document and share how you will integrate the
* technology
* teams
* leadership

### Dissent
Be a realist
Anchor your feedback to company goals, not engineerings
Speak now, or forever hold your peace

### Being Acquired
Depends on what kind of acquisition it is. 
* If a business acquisition, then nothing big will change overnight
* Conversely, if an acquihire, you might as well be starting a new job

The best thing you can do is fight for your team's compensation, then push the team to adapt quickly

## 8: Developing Leadership Styles

You need to be able to swap between three styles of leadership
* Process Oriented
* Consensus building
* Top down decision making

### Why executives need several leadership styles
Lead with Policy, not exceptions is good, but exceptions do need to be made and you are the one who must deal with them. 
* Lead with policy for recurring decisions where multiple people are affected
* Lead with consensus for infrequent decisions with context spread across multiple stakeholders
* Lead with conviction when there is no clear proposal, and the proponents are deeply divided

### Leading with Policy
Processes are the obvious things here, but outside that, documented criteria can help make many decisions

### Leading with Consensus
1. Pull together the relevant stakeholders so they can collectively make a decision. This works best when no one person has all the context. 
2. Is it an important decision? If not, just rule one way or the other and move on
3. Write a framing doc with the stakeholder opinions
4. Identify how the stakeholders will work together to make the decision. Give them a deadline
5. Make the most senior person run the process, this may be you

### Leading with Conviction
Use it more often than you think
1. Identify a scenario where no one had enough context to make the decision themselves and this won't repeat
2. Go deep with the people who have the most context
3. Write down a decision
4. Test the decision widely with people with context
5. Announce a tentative decision with stakeholders, and give a deadline for dissent
6. Finalise the decision
7. Write down your decision making process so others can understand
8. Move forward, acknowledging your good decision might end up a wrong one

This is not micromanagement, it's ok to review your team, to get feedback from their peers etc.
How to tell if you're micromanaging:
1. Are you considering the feedback of those closest to the work before making decisions?
2. Are you adding friction to a team that would have made a similar quality decision without you?
If you answer yes to .1 and no to 2. you're not micromanaging

### Development
1. Once a month, set aside an hour to collect all the problems you'll need to resolve
2. Identify within the list, a problem that could be solved using a style you don't use often
3. Do a thought exercise of solving that problem
4. Review your thought exercise with some who is good at that style
5. Compare that with a style you're comfortable with, which outcome is better?
6. If your uncomfortable scenario isn't much worse, and the stakes aren't too high, then give it a go

### Are you Disengaged?
The work could be too easy, or too difficult. If too easy, take on more work, if too difficult, identify your gaps and work on them

**Comment by elle** [comment]
Chapter 7:

Discussion around our experiences. And bottom line: it usually sucked, either technically or culturally.

Chapter 8:

We can reframe chapter 8 as a decision making framework. And is a process that you learn.

Leadership is not just about having authority to make decisions. 

Leadership is making a call that gets buy in, that promotes follow through, that is accepted and achieves something.

Are you poking holes above or below the the water line?

- Below the water line, is not the time to experiment and try new things
- Above the water line gives you more leeway

To make a good decision, it is important to: get the right people in the room, to ask the right questions, to have the right context

To make a good decision you also need to be empowered to make the decision, and not be afraid of taking the fall. One needs institutional support. And being held accountable if the decision that needs to be made is not being made.

You can't veto the team all the time, because that is dictatorship, and will deflate the team. Many times, you need to get buy-in from the wider team, to actually make the change stick.

You can make any decision you want, or write it in a policy, but it doesn't mean people will follow through. And achieving that, that is leadership
