### ISSUE TITLE
The Engineering Executive's Primer: July 31: chapters 9–11

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#226]
Book: [The Engineering Executive's Primer](https://lethain.com/eng-execs-primer/) by Will Larson

Aiming to read:

Chapters:
- 9: Managing Your Priorities and Energy
- 10: Meetings for an Effective Engineering Organisation
- 11: Internal Communications

MC: @lachlanhardy 
Notes: @mcgain

See you all at 12pm AEDT, July 31 @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via [gday@blackmill.co](mailto:gday@blackmill.co).

**Comment by elle** [comment]
# 9: Managing your priorities and energy

## “Company, Team, Self” Framework

- decision making around priorities
- Problem is that sometimes, we also want to prioritise the people, especially when planning for the long haul
- Generally this works until I am de-energised. And then prioritise energising work
- If the long-term balance between energy and proper priorities can’t be achieved for more than a year, stop everything else and work on solving this (e.g., change your role or quit).

[Not invented here](https://en.wikipedia.org/wiki/Not_invented_here)

> *there is almost always a “correct” answer, but applying that answer to your specific situation will always be nuanced and messy. Further, the correct answer is often different depending on whether you’re taking a short-term or long-term perspective.*
> 

## Mirrors of misalignment

> There is always another layer of context that validates or invalidates any given piece of work. This is why operating from a place of curiosity is so powerful: folks who appear to be doing something nonsensical almost always have more information than you, or are missing a key piece of information that you have.
 

> As an executive, each time this happens is a reminder to share your context more widely and remain curious. You’ll rarely be missing strategic context but you’ll increasingly be missing the tactical context around how things actually work.


## Orthogonal but not in opposition

- You can invest in people, as long it doesn’t end up hurting the organisation
- Examples:
    - For example, public speaking is great, but not if that takes over your working time
    - Learning new technologies can be energising work for you, but in many cases, it is likely in opposition to company’s needs

[RICE: Simple prioritization for product managers](https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers)

# 10: Meetings for an effective engineering organisation

[Tech Spec Review](https://infraeng.dev/tech-spec-review/)

[Incident Review](https://infraeng.dev/incident-review/)

## Six essential meetings

- Weekly leadership meeting - with a running agenda
- Weekly tech spec review and incident review
    - Concise, clearly written doc
    - Reading doc before meeting
    - Looking for a good discussion, not a presentation by author
- Monthlies with EMs and Staff Engineers
    - 15 mins: share what they’ve been working on, something they are excited about, and something they are working about
    - 30 mins: dev topic presentation
    - 15 mins: Q&A and closing
- Monthly Engineering Q&A

## Other meetings:

- One:ones
- Skip-levels
- Execution meetings
- Show-and-tells (demos)
- Tech talks (lunch and learn)
- Engineering all hands

## Scaling meetings

- Scale operational meetings to optimise for the right participants.
- Scale development meeting to optimise for participant engagement
- Keep Engineering Q&A as a whole org affair

> Great communication includes meetings but requires strong individual relationships and working through many other channels (e.g., email, chat), but all of these are easier to create on top of effective meetings.


# 11: Internal communications

- **Maintain the drip**
    - Weekly 5-15 email updates to show what you’ve focused on, what’s you’re doing, and re-assure that you’re paying attention to their work.
    - Format:
        - 1-2 sentences about something human, for example something that surprised/energised you this week
        - One sentence summarising key reminders for upcoming dates
        - One paragraph for each important topic that has come up during the week
        - Bulleted list of brief updates
        - Close with an invitation to reach out with questions, thoughts, and concerns

> When you get a question from an executive, focus on understanding the insight or perspective within the question. Then confirm that insight with the executive explicitly.

**Test before broadcasting**

- Especially when you’re new at the company
- Write comms and ask for feedback before sharing
- **Build the packet**
    - Concise summary: what has changed? Who does it apply to? What do I need to do if it applies to me? Where can I find more information? When is it happening? What should I do if I have questions?
    - Canonical source of information
    - Where to ask questions - along with a name individual
- Keep it short
- Use every channel
    - Email and chat
    - Meetings
    - Meeting minutes
    - Weekly notes: 5-15
    - [Decision log](https://infraeng.dev/decision-log/)
