### ISSUE TITLE
Leadership is Language: Sep 4: Intro + Chapter 1 

### ISSUE THREAD

**Issue by kunzmann** [Blackmill/book-club#231]
Book: The Engineering Executive's Primer by Will Larson

Aiming to read: Intro & Chapter 1

Chapters:

- Introduction (~16 pages)
- 1: Losing El Faro (~20 pages)

MC: @kunzmann
Notes: @elle 

See you all at 12pm AEDT, Sep 4 @ https://blackmill.whereby.com/bookclub

As always, if you'd like a calendar invite and/or access to Slack beforehand, get in touch via gday@blackmill.co.

**Comment by elle** [comment]
- Leadership is usually considered as making decisions from the top, but is that the best option?
- Even when the leader invites opinions, it depends on the language they use in the request and the power gradient between the leader and their reports. In chapter one, the officers on the bridge definitely did not feel comfortable speaking up.
- Good decision require two way communication - or no one have enough context. The people on the ground do not have the eagle-eye view but also the top leader doesn't know everything that happens on the ground.
- Hoping the book addresses how to ease people into the suggested team dynamics?
- Interested to see how a naval ship example tracks for other industries. A ship usually has one goal, but businesses sometimes have multiple goals.
- Maybe there is a competency baseline that doesn't always exists in tech companies. You can consider military training as a prolong onboarding
- Intention based communication is used in the military but also can be used at work, and is especially useful for async work environment - so people are not blocked waiting for permission
- Trying to get people to speak up is header when you are in an official role of authority. It can depend on how you ask questions but can still be challenging.
- Maybe the leader doesn't need to be in the meeting during the discussions - to give space for the team to feel more comfortable to come up with new ideas
