### ISSUE TITLE
Suggestions for next book to read

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#28]
Below is a list of the books that have been suggested in the past.
Please post any other book suggestions to this issue in comments.
Thanks

cc @lachlanhardy @HashNotAdam @mcgain @@nickspragg @antoinemacia

--

**Business-related:**

1. [An Elegant Puzzle](https://www.amazon.com/dp/B07QYCHJ7V/): systems of engineering management by Will Larson
  > _Management is a key part of any organization, yet the discipline is often self-taught and unstructured. Getting to the good solutions of complex management challenges can make the difference between fulfillment and frustration for teams, and, ultimately, the success or failure of companies._
2. [How to Measure Anything](https://www.amazon.com/How-Measure-Anything-Intangibles-Business/dp/1118539273) by Douglas Hubbard
  > _...shows managers how to inform themselves in order to make less risky, more profitable business decisions_
3. [Dare to Lead](https://www.amazon.com/dp/B07CWGFPS7/) by Brené Brown
  > _How do you cultivate braver, more daring leaders, and how do you embed the value of courage in your culture?_
4. [Conscious Business](https://www.amazon.com/Conscious-Business-Build-Through-Values-ebook/dp/B0034184XM) by Fred Kofman
  > _...fosters personal fulfillment in the individuals, mutual respect in the community, and success in the organization_
5. [Getting to Yes](https://www.amazon.com/Getting-Yes-Negotiating-Agreement-Without-ebook/dp/B0051SDM5Q) by Roger Fisher
  > _...offers a proven, step-by-step strategy for coming to mutually acceptable agreements in every sort of conflict._
6. [Powers of Two](https://www.amazon.com/Powers-Two-Relationships-Drive-Creativity-ebook/dp/B00E9FYT0O) by Joshua Wolf Shenk
  > _...draws on neuroscience, social psychology, and cultural history to present the social foundations of creativity, with the pair as its primary embodiment._
7. [The Essential Deming](https://www.amazon.com/dp/B00AK8FCEG/) by W. Edwards Deming
  > _Leadership Principles from the Father of Quality. It's a set of articles, essays, and notes on management and quality control._
8. [The Culture Code](https://www.amazon.com/Culture-Code-Secrets-Highly-Successful-ebook/dp/B01MSY1Y6Z/) by Daniel Coyle
  > _Where does great culture come from? How do you build and sustain it in your group, or strengthen a culture that needs fixing?_
9. [Unlearn](https://www.amazon.com/Unlearn-Success-Achieve-Extraordinary-Results-ebook/dp/B07HYBYBW7/) by Barry O'reilly
  > _This innovative and actionable framework from executive coach Barry O’Reilly shows leaders how to break the cycle and move away from once-useful mindsets and behaviors that were effective in the past but are no longer relevant in the current business climate and may now stand in the way of success._

**Programming-related:**

10. [Understanding Computation](https://www.amazon.com/Understanding-Computation-Machines-Impossible-Programs-ebook/dp/B00CT3C4IM) by Tom Stuart.
  > _...learn computation theory and programming language design in an engaging, practical way. Understanding Computation explains theoretical computer science in a context you’ll recognise, helping you appreciate why these ideas matter and how they can inform your day-to-day programming._
11. [Design Patterns in Ruby](https://www.amazon.com/Design-Patterns-Reader-Addison-Wesley-Professional-ebook/dp/B004YW6M6G) by Russ Olsen
  > _Fourteen of the classic "Gang of Four" patterns are considered from the Ruby point of view, explaining what problems each pattern solves, discussing whether traditional implementations make sense in the Ruby environment, and introducing Ruby-specific improvements. You'll discover opportunities to implement patterns in just one or two lines of code, instead of the endlessly repeated boilerplate that conventional languages often require._
12. [Growing Object-Oriented Software Guided by Tests](https://www.amazon.com/Growing-Object-Oriented-Software-Addison-Wesley-Signature-ebook/dp/B002TIOYVW) by Steve Freeman and Nat Pryce
  > _...describe the processes they use, the design principles they strive to achieve, and some of the tools that help them get the job done._
13. [Working Effectively with Legacy Code](https://www.amazon.com/Working-Effectively-Legacy-Code-EFFECT-ebook/dp/B005OYHF0A) by Michael Feathers
  > _...offers start-to-finish strategies for working more effectively with large, untested legacy code bases._
14. [Clean Architecture](https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure-ebook/dp/B075LRM681) by Bob Martin
  > _By applying universal rules of software architecture, you can dramatically improve developer productivity throughout the life of any software system._
15. [A Philosophy of Software Design](https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout-ebook/dp/B07N1XLQ7D/) by John Ousterhout
  > _how to decompose complex software systems into modules (such as classes and methods) that can be implemented relatively independently._
16. [A Mind for Numbers](https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra-ebook/dp/B00G3L19ZU/) by by Barbara Oakley
  > _The learning strategies in this book apply not only to math and science, but to any subject in which we struggle. We all have what it takes to excel in areas that don't seem to come naturally to us at first, and learning them does not have to be as painful as we might think!_

**Self exploration:**

17. [Daring Greatly](https://www.amazon.com/Daring-Greatly-Courage-Vulnerable-Transforms-ebook/dp/B007P7HRS4/) by Brene Brown
  > _How the courage to be vulnerable transforms the way we live, love, parent, and lead_ 
18. [Quiet revolution](https://www.quietrev.com) by Susan Cain
  > _Unlocking the power of introverts_
19. [The War of Art](https://www.amazon.com/War-Art-Steven-Pressfield-ebook/dp/B007A4SDCG) by Steven Pressfield
  > _...aims to help readers channel creative energy, unlock potential and overcome the fears that stop us from reaching our fullest potential._

**And more suggestions:**

20. The 20th anniversary edition of The Pragmatic Programmer will be released soon (in beta still, but it's off to print iirc).
The first edition was one of the foundational books of my career and I'm curious to see what they've updated.

21. Mindset Carol S Dweck
> Teaching a growth mindset creates motivation and productivity in the worlds of business, education, and sports.

22. Thinking Fast and Slow - Daniel Kahneman.

> The central thesis is a dichotomy between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical. The book delineates cognitive biases associated with each type of thinking, starting with Kahneman's own research on loss aversion.

**Comment by lachlanhardy** [comment]
My shortlist:

1, 7, 16.

**Comment by mcgain** [comment]
Book ideas:
Programming-related:
[The 20th anniversary edition of The Pragmatic Programmer](https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition) will be released soon (in beta still, but it's off to print iirc).
The first edition was one of the foundational books of my career and I'm curious to see what they've updated.

Self exploration:
[Mindset ](https://mindsetonline.com/) Carol S Dweck 
> Teaching a growth mindset creates motivation and productivity in the worlds of business, education, and sports.

**Comment by elle** [comment]
My current shortlist: 8, 3, 1

**Comment by elle** [comment]
@mcgain have you read the original pragmatic programmer? Loved the first edition.

Also love Carol Dweck. Have you seen any of her presentations?

**Comment by HashNotAdam** [comment]
2, 5, 10

**Comment by mcgain** [comment]
Edited my last comment to add thinking fast and slow

shortlist of the existing list:
10, 18, 19

@elle 
> The first edition (of the pragmatic programmer) was one of the foundational books of my career and I'm curious to see what they've updated.
As to Carol Dweck, I have her book in my to-read pile, no idea how it got there, but I must have seen or read something of hers.

**Comment by nickspragg** [comment]
My shortlist is:
2, 3, 17, 18

**Comment by antoinemacia** [comment]
My shortlist: 
The new Pragmatic Programmer edition, 19, 3, 2

**Comment by elle** [comment]
Current shortlist:

```
1 An elegant puzzle (2 votes)
2 How to measure everything (3 votes)
3 Dare to lead (3 votes)
10 Understanding computation (2 votes)
18 Quiet revolution (2 votes)
19 The war of art (2 votes)
```

Unless people change their votes by Tuesday (you're welcome to, can update the shortlist), we can decide/vote from this shortlist...

**Comment by stevegilles** [comment]
3, 4, 7, 18

**Comment by elle** [comment]
Adding [Measure what matters](https://www.whatmatters.com/book) for next round:

> Building on a career-long legacy of sharing the power of OKRs with established and emerging leaders alike, Measure What Matters includes a broad range of first-person accounts that demonstrate the focus, ambition, and explosive growth that OKRs have spurred at so many great organizations.

**Comment by lachlanhardy** [comment]
After some discussion, we decided to take a break from the leadership books despite the votes and chose [Understanding Computation](https://www.amazon.com/Understanding-Computation-Machines-Impossible-Programs-ebook/dp/B00CT3C4IM) by Tom Stuart instead.

  > _...learn computation theory and programming language design in an engaging, practical way. Understanding Computation explains theoretical computer science in a context you’ll recognise, helping you appreciate why these ideas matter and how they can inform your day-to-day programming._

**Comment by elle** [comment]
One more after the book club chat today: [Ruby Under the Microscope](http://patshaughnessy.net/ruby-under-a-microscope)
