### ISSUE TITLE
Understanding computations - Chapter 3 -  Tuesday Sep 24

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#34]
We're aiming to read and play with:

- Chapter 3: the simplest computers
  - Deterministic finite automata
  - Nondeterministic finite automata
  - Regular expressions

If you wish to share any code snippets to discuss next week, please upload them to:
https://github.com/Blackmill/book-club/tree/master/understanding-computation

MC: @HashNotAdam 
Notes: @saramic

See you 12pm Tuesday, September 24th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by lachlanhardy** [comment]
Even though we're all interested in this book, we've been struggling to find things to talk about so we're going to put it aside [in favour of Dare to Lead](https://github.com/Blackmill/book-club/issues/35) for now. However the plan is to continue with it on our own and do the Lambda Calculus section after we finish Dare To Lead. That should give everyone 5-6 weeks to get to the part everyone seemed most interested in.
