### ISSUE TITLE
Suggestions for next book club

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#36]
**Business-related:**

1. [The Essential Deming](https://www.amazon.com/dp/B00AK8FCEG/) by W. Edwards Deming
  > _Leadership Principles from the Father of Quality. It's a set of articles, essays, and notes on management and quality control._

2. [An Elegant Puzzle](https://www.amazon.com/dp/B07QYCHJ7V/): systems of engineering management by Will Larson
  > _Management is a key part of any organization, yet the discipline is often self-taught and unstructured. Getting to the good solutions of complex management challenges can make the difference between fulfillment and frustration for teams, and, ultimately, the success or failure of companies._

3. [How to Measure Anything](https://www.amazon.com/How-Measure-Anything-Intangibles-Business/dp/1118539273) by Douglas Hubbard
  > _...shows managers how to inform themselves in order to make less risky, more profitable business decisions_

4. [Conscious Business](https://www.amazon.com/Conscious-Business-Build-Through-Values-ebook/dp/B0034184XM) by Fred Kofman
  > _...fosters personal fulfillment in the individuals, mutual respect in the community, and success in the organization_

5. [Thinking Fast and Slow](https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555) by Daniel Kahneman.
  > _The central thesis is a dichotomy between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical. The book delineates cognitive biases associated with each type of thinking, starting with Kahneman's own research on loss aversion._

6. [Getting to Yes](https://www.amazon.com/Getting-Yes-Negotiating-Agreement-Without-ebook/dp/B0051SDM5Q) by Roger Fisher
  > _...offers a proven, step-by-step strategy for coming to mutually acceptable agreements in every sort of conflict._

7. [Powers of Two](https://www.amazon.com/Powers-Two-Relationships-Drive-Creativity-ebook/dp/B00E9FYT0O) by Joshua Wolf Shenk
  > _...draws on neuroscience, social psychology, and cultural history to present the social foundations of creativity, with the pair as its primary embodiment._

8. [The Culture Code](https://www.amazon.com/Culture-Code-Secrets-Highly-Successful-ebook/dp/B01MSY1Y6Z/) by Daniel Coyle
  > _Where does great culture come from? How do you build and sustain it in your group, or strengthen a culture that needs fixing?_

9. [Unlearn](https://www.amazon.com/Unlearn-Success-Achieve-Extraordinary-Results-ebook/dp/B07HYBYBW7/) by Barry O'reilly
  > _This innovative and actionable framework from executive coach Barry O’Reilly shows leaders how to break the cycle and move away from once-useful mindsets and behaviours that were effective in the past but are no longer relevant in the current business climate and may now stand in the way of success._

10. [Leadership & Self-deception: Getting Out Of The Box](https://www.amazon.com/Leadership-Self-Deception-Getting-Out-Box/dp/1523097809) by The Arbinger Institute
  > __Leadership and Self-Deception_ uses an entertaining story everyone can relate to about a man facing challenges at work and at home to expose the fascinating ways that we blind ourselves to our true motivations and unwittingly sabotage the effectiveness of our own efforts to achieve happiness and increase happiness. We trap ourselves in a "box" of endless self-justification. Most importantly, the book shows us the way out._

11. [Doing Good Better](https://www.effectivealtruism.org/doing-good-better/) by William MacAskill
  > _In Doing Good Better MacAskill introduces the principles underlying effective altruism and sets out a practical guide to increasing your impact through your charity, volunteering, purchases and choice of cause._

**Programming-related:**

12. [The 20th anniversary edition of The Pragmatic Programmer](https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition) by by David Thomas and Andy Hunt

13. [Ruby under a microscope](http://patshaughnessy.net/ruby-under-a-microscope) by Pat Shaughnessy
  > _Ruby Under a Microscope will guide you through the internals of some of Ruby's most-used facets. Using experimentation, theory, and two truckloads of diagrams, you'll clearly see how Ruby is implemented._

14. [Design Patterns in Ruby](https://www.amazon.com/Design-Patterns-Reader-Addison-Wesley-Professional-ebook/dp/B004YW6M6G) by Russ Olsen
  > _Fourteen of the classic "Gang of Four" patterns are considered from the Ruby point of view, explaining what problems each pattern solves, discussing whether traditional implementations make sense in the Ruby environment, and introducing Ruby-specific improvements. You'll discover opportunities to implement patterns in just one or two lines of code, instead of the endlessly repeated boilerplate that conventional languages often require._

15. [Growing Object-Oriented Software Guided by Tests](https://www.amazon.com/Growing-Object-Oriented-Software-Addison-Wesley-Signature-ebook/dp/B002TIOYVW) by Steve Freeman and Nat Pryce
  > _...describe the processes they use, the design principles they strive to achieve, and some of the tools that help them get the job done._

16. [Working Effectively with Legacy Code](https://www.amazon.com/Working-Effectively-Legacy-Code-EFFECT-ebook/dp/B005OYHF0A) by Michael Feathers
  > _...offers start-to-finish strategies for working more effectively with large, untested legacy code bases._

17. [Clean Architecture](https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure-ebook/dp/B075LRM681) by Bob Martin
  > _By applying universal rules of software architecture, you can dramatically improve developer productivity throughout the life of any software system._

18. [A Philosophy of Software Design](https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout-ebook/dp/B07N1XLQ7D/) by John Ousterhout
  > _how to decompose complex software systems into modules (such as classes and methods) that can be implemented relatively independently._

**Self exploration/learning:**

19. [A Mind for Numbers](https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra-ebook/dp/B00G3L19ZU/) by by Barbara Oakley
  > _The learning strategies in this book apply not only to math and science, but to any subject in which we struggle. We all have what it takes to excel in areas that don't seem to come naturally to us at first, and learning them does not have to be as painful as we might think!_

20. [Mindset](https://mindsetonline.com) by Carol S Dweck
  > _Teaching a growth mindset creates motivation and productivity in the worlds of business, education, and sports._

21. [Make It Stick: The Science of Successful Learning](https://www.amazon.com/Make-Stick-Science-Successful-Learning/dp/B00M1Z2THY/)
  > _Make It Stick turns fashionable ideas like these on their head. Many common study habits and practice routines turn out to be counterproductive. Underlining and highlighting, rereading, cramming, and single-minded repetition of new skills create the illusion of mastery, but gains fade quickly. More complex and learning come from self-testing, introducing certain difficulties in practice, waiting to re-study new material until a little forgetting has set in, and interleaving the practice of one skill or topic with another. Speaking most urgently to students, teachers, trainers, and athletes, Make It Stick will appeal to all those interested in the challenge of lifelong learning and self-improvement._

22. [Daring Greatly](https://www.amazon.com/Daring-Greatly-Courage-Vulnerable-Transforms-ebook/dp/B007P7HRS4/) by Brene Brown
  > _How the courage to be vulnerable transforms the way we live, love, parent, and lead_ 

23. [Quiet revolution](https://www.quietrev.com) by Susan Cain
  > _Unlocking the power of introverts_

24. [The War of Art](https://www.amazon.com/War-Art-Steven-Pressfield-ebook/dp/B007A4SDCG) by Steven Pressfield
  > _...aims to help readers channel creative energy, unlock potential and overcome the fears that stop us from reaching our fullest potential._

**Comment by lachlanhardy** [comment]
Aimee suggested [Leadership & Self-deception](https://www.amazon.com/Leadership-Self-Deception-Getting-Out-Box/dp/1523097809)

**Comment by mcgain** [comment]
Not sure anyone would be in to it, as it's a bit of a departure from our usual fare, but: 
https://www.effectivealtruism.org/doing-good-better/

**Comment by agc0610** [comment]
If (when!) we read An Elegant Puzzle, I can try to organise an author session if the group would like-- Will is a friend, and is interested in getting out there in more of an author way so I'm sure he'd be keen to connect with readers. :)

**Comment by lachlanhardy** [comment]
Oooh! That could be super intense. I like it.

**Comment by lachlanhardy** [comment]
I've edited the issue to add the other suggested books. Let's make some shortlists! List your top 3 (or so) preferences and we'll use that as a base of discussion today.

**Comment by lachlanhardy** [comment]
My shortlist: 2, 11, 21.

**Comment by HashNotAdam** [comment]
12, 19, 3

**Comment by lachlanhardy** [comment]
Richard: 12, 5, 11.
Antoine: 12, 2, 24.
Aimee: 5, 2.
Elle: 12, 2, 5.

We narrowed it down to 12, 2, 5. And settled on:

5. [Thinking Fast and Slow](https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555) by Daniel Kahneman.
  > _The central thesis is a dichotomy between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical. The book delineates cognitive biases associated with each type of thinking, starting with Kahneman's own research on loss aversion._

**Comment by elle** [comment]
Adding [Nudge: Improving Decisions About Health, Wealth, and Happiness](https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness/dp/014311526X)

> From the winner of the Nobel Prize in Economics, Richard H. Thaler, and Cass R. Sunstein: a revelatory look at how we make decisions—for fans of Malcolm Gladwell’s Blink and Daniel Kahneman’s Thinking, Fast and Slow

> “One of the few books . . . that fundamentally changes the way I think about the world.” —Steven D. Levitt, coauthor of Freakonomics
