### ISSUE TITLE
October 15: Dare to lead: Chapters 3 and 4

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#38]
Aiming to read:

Section three: the armory
Section four: shame and empathy

MC: @mcgain 
Notes: @antoinemacia

See you 12pm Tuesday, October 15th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by lachlanhardy** [comment]
notes file updated: https://github.com/Blackmill/book-club/blob/master/dare-to-lead.md
