### ISSUE TITLE
October 22: Dare To Lead - Chapters 3 & 4

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#39]
We're up to the 12th example of Armoured Leadership in Chapter 3 so we'll start there and move into Chapter 4.

MC: @lachlanhardy  
Notes: @mcgain

See you 12pm Tuesday, October 22nd @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
Notes added
