### ISSUE TITLE
Nov 26: Dare to lead: Part 3 and Part 4

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#42]
Aiming to read:

- Part three: Braving trust
- Part four: Learning to rise

MC: @mcgain 
Notes: @HashNotAdam 

See you 12pm Tuesday, November 8th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
My notes from part 3:
## Part 3: Braving trust

> Integrity is choosing courage over comfort.
> It's choosing what's right over what's fun, fast, or easy; and it's practising your values, not just professing them.

When someone questions your trustworthiness, we go into vulnerability lockdown. Hijacked by limbic system

Reminds me of Lara's Hogan book...

> We all want to believe that we are trustworthy, even though, ironically, many of us struggle to trust others.

--
> Feltman defines trust as "choosing to risk making something you value vulnerable to another person's actions." He describes distrust as deciding that "what is important to me is not safe with this person in this situation (or any situation)."

When there are trust issues:

- Conversations is not direct and waste a lot of energy
- Trust holds teams and organisations together, thus lack of trust results in poor performance and compromised team success

> Fortune's research showed that "trust between managers and employees is the primary defining characteristic of the very best workplaces,” and that companies with high levels of trust “beat the average annualized returns of the S&P 500 by a factor of three."

### Trust talk we can actually hear

Instead of saying: "you didn't get the promotion because of trust issues",  talk about actionable strategies for changing what's problematic.

#### Trust inventory

- Boundaries - when not clear, ask, and it's ok to say no
- Reliability - own your deliverables and priorities
- Accountability - own your mistakes
- Vault - don't share what is not yours to share
- Integrity - choose courage over comfort
- Non-judgement - talk about how we feel without judgement, same when asking for help
- Generosity - in interpretation of intentions, words and actions of others

> Asking for help is a power move. It’s a sign of strength to ask and a sign of strength to fight off judgment when other people raise their hands. It reflects a self-awareness that is an essential element in braving trust.

--
> There’s a terrible pattern in organizations in which leaders turn to their teams, or their investors, or their board, and say “You need to trust me.” Typically, that happens in a moment of crisis, when it is far too late. Trust is the stacking of small moments over time, something that cannot be summoned with a command -- there are either marbles in the jar or there are not


### Self trust

> While trust is inherently relational and most pronounced in practice with other people, the foundation of trust with others is really based on our ability to trust ourselves.

**Comment by HashNotAdam** [comment]
## Receiving feedback

```
Elle: Not everyone can give feedback in a constructive way.
If you put aisde the confronting nature of it, you can learn a lot

Richard: There was valuable discussion about understanding where people are coming from but there is also a lot of angry feedback that is given and sometimes in an unprofessional way. So you really need to understand where people are coming from and understand that people can be angry but sometimes you do have to call people on their behaviour.
```

## Values

While it can be valuable to decide upon and document company values, converting them into behaviours makes them more liveable.

```
Antoine: when you are forced to identifiy behaviours that support your core values, you can realise that the values you believe are core might not be.

Richard: It is possible that testing for company values might reduce diversity.

Lachlan: Selecting/understanding your values is really tough because you can believe strongly in something without it being a core value.
```

# Part Three — Braving Trust

When our trustwothiness is questioned, we begin a vulnerability lockdown. Most of us believe we are trustworthy yet we struggle to trust others.

> When we’re struggling with trust and don’t have the tools or skills to talk about it directly with the person involved, it leads us to talk about people instead of to them.
>

## The BRAVING Inventory

**Boundaries:** You respect my boundaries, and when you’re not clear about what’s okay and not okay, you ask. You’re willing to say no.
**Reliability:** You do what you say you’ll do. At work, this means staying aware of your competencies and limitations so you don’t overpromise and are able to deliver on commitments and balance competing priorities
**Accountability:** You own your mistakes, apologize, and make amends.
**Vault:** You don’t share information or experiences that are not yours to share.

```
Richard: Had a situation where it was necessary to deal with an issue but speaking about it would break confidence and, as such, chose to invent a new story to allow the issue to be resolved without breaking trust. It's hard to know if this was the right choice but it did ensure trust was not broken.
```

**Integrity:** You choose courage over comfort.

```
Lachlan: Coming from the army, the idea of integrity and "doing what's right" is always front of mind but how do you define "right"?
```

**Nonjudgment:** I can ask for what I need, and you can ask for what you need.
**Generosity:** You extend the most generous interpretation possible to the intentions, words, and actions of others.

## The Basics of Self-Trust

**Boundaries:** Did I respect my own boundaries in the situation?
**Reliability:** Could I count on myself?
**Accountability:** Did I hold myself accountable or did I blame others? And did I hold others accountable when I should have?
**Vault:** Did I honor the vault, and did I share, or not share, appropriately? Did I stop other people who were sharing inappropriately?
**Integrity:** Did I choose courage over comfort?
**Nonjudgment:** Did I ask for help when I needed it? Was I judgmental about needing help? Did I practice nonjudgment with myself?
**Generosity:** Was I generous toward myself? Did I talk to myself with kindness and respect and like someone I love?

# Part Four — Learning to Rise

Teaching leaders to be resilient before they have experienced a fall allows them to be brave.

### The Reckoning

> We are emotional beings, and when something hard happens to us, emotion drives.

> The reckoning is as simple as that: knowing that we’re emotionally hooked and then getting curious about it.

> Very few people make it through the reckoning, for one reason: Instead of feeling our emotions and getting curious, we offload them onto others.

### Offloading Strategies

**1) Chandeliering:** when the pain is so severe that touching it makes you jump to the chandelier.
**2) Bouncing Hurt:** it’s much easier to say “I don’t give a damn” than it is to say “I’m hurt.”
**3) Numbing Hurt:** in addition to numbing being a popular form of armor, we can offload emotion through it as well.
**4) Stockpiling Hurt:** Stockpiling starts like chandeliering, by firmly packing down the pain, but instead of unleashing it on another person, we just continue to amass hurt until our bodies decide that enough is enough.
**5) The Umbridge:** when light and dark are not integrated, overly sweet and accommodating can feel foreboding, as though under all that niceness is a ticking bomb.
**6) Hurt and the Fear of High-Centering:** getting stuck in a way that makes it difficult to go forward or backward.

```
Lachlan: There is a theory that Einstein was helped by having a boring job. This allowed his brain the time to think on the bigger issues. Had he been using all of his brain at work, maybe he wouldn't have had the great breakthroughs.

Richard: It is possible to be overstimulated, particularly given the availability of podcasts, Twitter, etc. Your brain needs time to relax and, if you don't get it, productivity plummets.

Elle: Has this problem but it's an internal conflict because she doesn't want to give up on the benefits of learning. Recently asked if she misses living in Fiji—one of the great things about living there is that "there is nothing to do" and so you have the time. The balance is learning when to say "I don't need to learning this now".
```
