### ISSUE TITLE
Thinking fast and slow: chapters 10-13: Jan 21

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#48]
Aiming to read:
Chapter 10: The Law of Small Numbers
Chapter 11: Anchors
Chapter 12: The Science of Availability
Chapter 13: Availability, Emotion, and Risk

MC: @HashNotAdam 
Notes: @antoinemacia 

See you 12pm Tuesday, Jan 21st @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
# 10: the law of small numbers

We automatically and effortlessly identify causal connections between events, even when the connection is spurious.

Question is: how do we avoid making those assumptions?

> a mathematical fact: samples of 4 marbles yield extreme results more often than samples of 7 marbles do.

--
> - Large samples are more precise than small samples
> - Small samples yield extreme results more often than large samples do

Talking about manipulating research samples...

> Using a sufficiently large sample is the only way to reduce the risk. Researchers who pick too small a sample leave themselves at the mercy of sampling luck. 

--
> The message about the poll contains information of two kinds: the story and the source of the story. Naturally, you focus on the story rather than on the reliability of the results. 

System 1 doesn't doubt, that is the role of system 2. However, sustaining doubt is harder work than sliding into certainty.

Side note: Don't make me think, by Steven Krug

### Cause and chance

> assuming causality could have had evolutionary advantages. It is part of the general vigilance that we have inherited from ancestors. We are automatically on the lookout for the possibility that the environment has changed.

--
> “To the untrained eye,” Feller remarks, “randomness appears as regularity or tendency to cluster.”

--
> The tendency to see patterns in randomness is overwhelming... if you follow your intuition, you will more often than not err by misclassifying a random event as systematic. We are far too willing to reject the belief that much of what we see in life is random. 

In summary: having faith in small numbers is an illusion and leads to more extreme results. So we are better off with bigger sample sizes. and finding causal explanations in statistics is easier more than it is correct.

Side note: making small "agile" experiments

# 11: Anchors

> Any number that you are asked to consider as a possible solution to an estimation problem will induce an anchoring effect. 

### Deliberate system 2 adjustment
When an anchor is set, you then adjust the estimate until it is far enough from the anchor that you are no longer sure it is valid... you are likely to stop when you are no longer sure you should go farther

### Anchoring as priming effect
Suggestion is a priming effect.

> any prime will tend to evoke information that is compatible with it. Suggestion and anchoring are both explained by the same automatic operation of System 1.

### The anchoring index
The anchoring index is simply the ratio of the two differences (range or distance in answers/range or distance in anchors) expressed as a percentage.

The anchoring index would be 100% if people accepted the anchor as an estimate. It would be zero for people who ignore the anchor. An index of 55% is typical.

> When no anchor was mentioned, the visitors at the Exploratorium—generally an environmentally sensitive crowd—said they were willing to pay $64, on average. When the anchoring amount was only $5, contributions averaged $20. When the anchor was a rather extravagant $400, the willingness to pay rose to an average of $143.

--
> The “estimate” in fine-art auctions is also an anchor that influences the first bid.

When you know next to nothing about a topic, it is easier to stick to or close to the anchor.

> anchors that are obviously random can be just as effective as potentially informative anchors... clear: anchors do not have their effects because people believe they are informative.

### Uses and abuses of anchors
> moving first is an advantage in single-issue negotiations—for example, when price is the only issue to be settled between a buyer and a seller.

In negotiations either decline to continue with an outrageous number as an anchor, or consciously active system 2 to find arguments to negate that anchor. For example if you focus on a different valid number in the negotiation ("thinking the opposite").

> the anchoring effect is reduced or eliminated when the second mover focuses his attention on the minimal offer that the opponent would accept, or on the costs to the opponent of failing to reach an agreement.

Side note: when writing feature stories, avoid suggesting a solution. Instead focus on the problem and leave the options on how to solve it open.

# 12: the science of availability

> defined the availability heuristic as the process of judging frequency by "the ease with which instances come to mind."...

but really no instances are needed

> The availability heuristic, like other heuristics of judgment, substitutes one question for another: you wish to estimate the size of a category or the frequency of an event, but you report an impression of the ease with which instances come to mind.

Side note: number of shark attacks vs car accidents

> Maintaining one’s vigilance against biases is a chore—but the chance to avoid a costly mistake is sometimes worth the effort. 

--
> You will occasionally do more than your share, but it is useful to know that you are likely to have that feeling even when each member of the team feels the same way. 

Side note: this seems too logical to me, when a person is emotional.

### The psychology of availability

- Amount: How many instances were you able to retrieve?
- Ease and fluency: How easy did they come to mind?

But which counts more?

> The contest yielded a clear-cut winner: people who had just listed twelve instances rated themselves as less assertive than people who had listed only six...The experience of fluent retrieval of instances trumped the number retrieved. 

--
> As expected, the students who listed more ways to improve the class rated it higher! 

Side note: get people to guide themselves on a dive, and they will not complain the dive was boring

> Perhaps the most interesting finding of this paradoxical research is that the paradox is not always found: people sometimes go by content rather than by ease of retrieval. The proof that you truly understand a pattern of behavior is that you know how to reverse it. 

--
> In Schwarz’s experiment, the background music has been mentioned as a possible cause of retrieval problems. The difficulty of retrieving twelve instances is no longer a surprise and therefore is less likely to be evoked by the task of judging assertiveness.

--
> reliance on intuition is only in part a personality trait. Merely reminding people of a time when they had power increases their apparent trust in their own intuition.

# 13: Availability, emotion, and risk

> The dynamics of memory help explain the recurrent cycles of disaster, concern, and growing complacency 

--
> The lesson is clear: estimates of causes of death are warped by media coverage. The coverage is itself biased toward novelty and poignancy. The media do not just shape what the public is interested in, but also are shaped by it. Editors cannot ignore the public’s demands that certain topics and viewpoints receive extensive coverage. Unusual events (such as botulism) attract disproportionate attention and are consequently perceived as less unusual than they really are. The world in our heads is not a precise replica of reality; our expectations about the frequency of events are distorted by the prevalence and emotional intensity of the messages to which we are exposed. 

- Ease of retrieval of instances, and
- the emotional reaction they invoke
- is linked to perceived risk

> The affect heuristic is an instance of substitution, in which the answer to an easy question (How do I feel about it?) serves as an answer to a much harder question (What do I think about it?). 

--
> people who do not display the appropriate emotions before they decide, sometimes because of brain damage , also have an impaired ability to make good decisions. An inability to be guided by a “healthy fear” of bad consequences is a disastrous flaw. 

If we like something, it has few costs. If we don't, it has no benefits. This is a very simplified way of looking at the world. But in the real world, there are always tradeoffs between benefits and costs.

### The public and experts

> experts often measure risks by the number of lives (or life-years) lost, while the public draws finer distinctions, for example between “good deaths” and “bad deaths,” or between random accidental fatalities and deaths that occur in the course of voluntary activities such as skiing. 

There is no such thing as "real risk" or "objective risk"
Side note: same debate as: is anything the world objective?
