### ISSUE TITLE
Thinking fast and slow: chapters 14-17: Jan 28

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#49]
Aiming to read:
Chapter 14: Tom W's specialty
Chapter 15: Linda: less is more
Chapter 16: Causes trump statistics
Chapter 17: Regression to the mean

MC: @elle 
Notes: @HashNotAdam

See you 12pm Tuesday, Jan 28st @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by elle** [comment]
# 14: Tom W's Specialty

What field is Tom in? Do you decide based on relative size of the different departments? or similarity of description to stereotypes (_representativeness_)?

> The representativeness heuristic is involved when someone says “She will win the election; you can see she is a winner” or “He won’t go far as an academic; too many tattoos.” We rely on representativeness when we judge the potential leadership of a candidate for office by the shape of his chin or the forcefulness of his speeches.
> 
> Although it is common, prediction by representativeness is not statistically optimal

--
> Judging probability by representativeness has important virtues: the intuitive impressions that it produces are often—indeed, usually—more accurate than chance guesses would be.

### Bayesian statistics

Bayes' rule define how prior beliefs should be combined with diagnosticity of the evidence, the degree in which it favours the hypothesis over the alternative.

**How to?**

- Anchor your judgment of probability of an outcome on a plausible rate base
- Question the diagnosticity of your evidence.

For example: 3% of students are in computer sciences. Tom is 4 times more likely to be in computer sciences. Therefore the chance he is a com sci student is 11%.

# 15: Linda: less is more

> When you specify a possible event in greater detail you can only lower its probability.

> Which alternative is more probable?  
> - Linda is a bank teller.  
> - Linda is a bank teller and is active in the feminist movement. 

But in Linda's case, everyone ranked "feminist bank teller" more than just plain old "bank teller". Even though, when you consider just these two options, there is a greatest chance Linda is a bank teller, because it is more generic in nature.

> the idea of a _conjunction fallacy_, which people commit when they judge a conjunction of two events (here, bank teller and feminist) to be more probable than one of the events (bank teller) in a direct comparison. 

--
> Representativeness belongs to a cluster of closely related basic assessments that are likely to be generated together. The most representative outcomes combine with the personality description to produce the most coherent stories. The most coherent stories are not necessarily the most probable, but they are plausible , and the notions of coherence, plausibility, and probability are easily confused by the unwary.

**Basically, less description is more probable**

Dinnerware sets: one small and intact, one bigger with broken pieces:
no one wants to pay for broken dishes, so even though one set is smaller (less), its value is higher.

> People who see the dinnerware set that includes broken dishes put a very low price on it; their behavior reflects a rule of intuition. Others who see both sets at once apply the logical rule that more dishes can only add value. Intuition governs judgments in the between-subjects condition; logic rules in joint evaluation. 

Health survey of adult males:

> The solution to the puzzle appears to be that a question phrased as “how many?” makes you think of individuals, but the same question phrased as “what percentage?” does not.

> If you visit a courtroom you will observe that lawyers apply two styles of criticism: to demolish a case they raise doubts about the strongest arguments that favor it; to discredit a witness, they focus on the weakest part of the testimony. The focus on weaknesses is also normal in political debates. I do not believe it is appropriate in scientific controversies, but I have come to accept as a fact of life that the norms of debate in the social sciences do not prohibit the political style of argument, especially when large issues are at stake—and the prevalence of bias in human judgment is a large issue. 

# 16: causes trump statistics

### Causal stereotypes

> The conclusion is immediate: the Green drivers must be a collection of reckless madmen! You have now formed a stereotype of Green recklessness, which you apply to unknown individual drivers in the company. 

Side note: Really?? There is a difference between people answering a question, and knowing the mental processes behind their way of thinking.
This book continues to prove that lay people are not statisticians by nature.

> The two types of base-rate information are treated differently:
> 
> - Statistical base rates are generally underweighted, and sometimes neglected altogether, when specific information about the case at hand is available.
> 
> - Causal base rates are treated as information about the individual case and are easily combined with other case-specific information.

Statements:

- Most of the graduates of this inner-city school go to college.
- Interest in cycling is widespread in France.

> stereotypes, both correct and false, are how we think of categories.

--
> We consider it morally desirable for base rates to be treated as statistical facts about the group rather than as presumptive facts about individuals. In other words, we reject causal base rates.

Randomly: "It also supports the uncomfortable conclusion that teaching psychology is mostly a waste of time." Really?

> individuals feel relieved of responsibility when they know that others have heard the same request for help.

--
> individuals feel relieved of responsibility when they know that others have heard the same request for help.

--
> Nisbett and Borgida found that when they presented their students with a surprising statistical fact, the students managed to learn nothing at all. But when the students were surprised by individual cases—two nice people who had not helped—they immediately made the generalization and inferred that helping is more difficult than they had thought.

**You are more likely to learn something by finding surprises in your own behavior than by hearing surprising facts about people in general.**

# 17: Regression to the mean

> Naturally, he praised only a cadet whose performance was far better than average. But the cadet was probably just lucky on that particular attempt and therefore likely to deteriorate regardless of whether or not he was praised. Similarly, the instructor would shout into a cadet’s earphones only when the cadet’s performance was unusually bad and therefore likely to improve regardless of what the instructor did. The instructor had attached a causal interpretation to the inevitable fluctuations of a random process. 

--
> poor performance was typically followed by improvement and good performance by deterioration, without any help from either praise or punishment.

### Talent and luck

Success = talent + luck
Great success = a little more talent + a lot more luck

Side note: very fatalistic

Best predicted performance after a successful attempt, is more moderate performance, basically, closer to average. The more extreme the original performance, the more regression will happen.

Players that had better performance on day 1, was probably because of more luck. Therefore, on day 2, they might have less luck, and have more average performance.

**Regression does not have a causal explanation.**

> Overconfidence and the pressure of meeting high expectations are often offered as explanations. But there is a simpler account of the jinx: an athlete who gets to be on the cover of Sports Illustrated must have performed exceptionally well in the preceding season, probably with the assistance of a nudge from luck—and luck is fickle. 

--
> The point to remember is that the change from the first to the second jump does not need a causal explanation. It is a mathematically inevitable consequence of the fact that luck played a role in the outcome of the first jump. 

### Understanding regression

> The **correlation coefficient** between two measures, which varies between 0 and 1, is a measure of the relative weight of the factors they share. 
> 
> - The correlation between income and education level in the United States is approximately .40.
> - The correlation between family income and the last four digits of their phone number is 0. 

Correlation and regression are different perspectives on the same concept: whenever the correlation between two scores is imperfect, there will be regression to the mean. 

Memories once again interfere with plain statistics.

**Comment by HashNotAdam** [comment]
### Conversation notes

Lachlan found the chapters quite boring.

Elle: "It doesn't matter how much you work, you still need some luck in there which makes it sad"

Richard: "I really enjoyed this regression to the mean chapter. Although I can't think of any circumstances where it applies to me recently, I think it will come up .... this will be a good reminder someday"
