### ISSUE TITLE
Suggested books

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#5]
1. [Conscious Business](https://www.amazon.com/Conscious-Business-Build-Through-Values-ebook/dp/B0034184XM): how to build value through values
1. [Conflict without casualties](https://www.amazon.com/Conflict-without-Casualties-Compassionate-Accountability-ebook/dp/B01N4RE97O/): a field guide for leading with compassionate accountability
1. [Understanding Computation](https://www.amazon.com/Understanding-Computation-Machines-Impossible-Programs-ebook/dp/B00CT3C4IM) by Tom Stuart
1. [Design patterns in Ruby](https://www.amazon.com/Design-Patterns-Reader-Addison-Wesley-Professional-ebook/dp/B004YW6M6G) by Russ Olsen
1. [Growing Object-Oriented Software Guided by Tests](https://www.amazon.com/Growing-Object-Oriented-Software-Addison-Wesley-Signature-ebook/dp/B002TIOYVW) - Nat Pryce
1. [Working effectively with legacy code](https://www.amazon.com/Working-Effectively-Legacy-Code-EFFECT-ebook/dp/B005OYHF0A)
1. [Clean Architecture](https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure-ebook/dp/B075LRM681) by Bob Martin
1. [Quiet revolution: unlocking the power of introverts](https://www.quietrev.com)

**Comment by lachlanhardy** [comment]
We're taking next Tuesday off, but we'll make a decision what book by then, so people have time to buy and read the first couple of chapters.

**Comment by lachlanhardy** [comment]
@nickspragg has shortlisted 1, 2, and 8.
@elle wants all of them as it is her list.
My preference is for 2 or 3.

**Comment by SophieRoseMcDonald** [comment]
I am interested in 1, 2 and 4.

**Comment by lachlanhardy** [comment]
Seems the consensus is for option 2: [Conflict without casualties](https://www.amazon.com/Conflict-without-Casualties-Compassionate-Accountability-ebook/dp/B01N4RE97O/): a field guide for leading with compassionate accountability

@saramic @davich @cattekin Are you up for this too?

**Comment by lachlanhardy** [comment]
Okay, so let's just run with it. I've created a new issue: https://github.com/Blackmill/book-club/issues/9

See you next week!
