### ISSUE TITLE
Thinking fast and slow: chapters 29–32: Tue 25th

### ISSUE THREAD

**Issue by HashNotAdam** [Blackmill/book-club#53]
Aiming to read:
Chapter 29: The Fourfold Pattern
Chapter 30: Rare Events
Chapter 31: Risk Policies
Chapter 32: Keeping Score

MC: @antoinemacia
Notes: @HashNotAdam

See you 12 pm Tuesday, Feb 25th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by HashNotAdam** [comment]
**@lachlanhardy:** The point of the book isn't to stop you from feeling the effects, such as loss aversion, but create mitigation strategies.

**@mcgain:** Doesn't believe that the calculation for evaluating risk (return multiplied by probability) makes sense unless you get multiple attempts.

**@lachlanhardy:** Thanks to these chapters, he is now thinking of everything as a gamble. Even buying shaving cream can be a gamble. Should you try a cheaper one? You might save but you might also end up throwing it out.
**@elle:** Always take the sure thing; wants to be certain of a win regardless of the probability. Everything you order at a restaurant is a gamble but those gambles make life exciting where the risk is tiny.

**@HashNotAdam:** When it is mentioned that if you take a certain \$500 over 98% chance of \$520k, you are "violating the rules of rational choice". Is there such a thing as The Rules of Rational Choice or is this his description?
**@lachlanhardy:** The rules are defined by Rational Choice Theory. The original economic theory assumed that people were rational but the research behind the book showed this isn't the case. This comes back to Richard's earlier thought that if you get the option once, you should take certainty but if you get it many times you should take the risk.
**@HashNotAdam:** Except that in chapter 31 the mantra states "you will do yourself a large financial favour if you are able to see each of these gambles as part of a bundle of small gambles". This is, of course, nonsensical given the examples because when are you going to be offered a free $500k again in your life‽

**@antoinemacia:** The recent chapters show how we are "beasts of emotion" and there are many businesses who's success is reliant upon our anxieties and emotions.

@elle mused that insurance costs are called "premiums" because we pay above the value of what is being insured.

The framing of so much of life as gambling is causing some distress.

**@antoinemacia:** Insurance provides protection from regret and so those who are in a healthy financial position might get a lot of insurance, despite their capacity to pay the cost of disaster, just to avoid that regret.

**Interesting note:** If you take two cows to the bank, they'll give you a horse.

**@HashNotAdam:** Take away from chapter 29 was that people assign too great a value on risk as evidenced by parents accepting an increase in cost of ~24% to reduce a tiny risk by ⅔ but ~81% to completely remove a tiny risk. It was later discussed that this could include elements of fear of regret or, as it was "delicately" put in the book, parents might be "motivated by a selfish fear of regret more than by a wish to optimize the child’s safety".
**@elle:** In this particular case, "actual figures don't make sense... he should really give percentages".
**@lachlanhardy:** The discussion of framing (0.05% vs 15 children in every thousand) from the next chapter gives this necessary context. "You literally go 'that's my child being poisoned, of course I'll pay $8 to fix it!'"
**@elle:** "Our brains don't work well with statistics."

**@lachlanhardy:** Wanted to see a deeper analysis of the decision weights table. If charted, it makes an interesting snake pattern but with one end sharper than the other.
**@mcgain:** Felt the decision weights matched his views perfectly.
<img width="525" alt="probability vs decision weight" src="https://user-images.githubusercontent.com/902714/75212580-7b852880-57db-11ea-8b14-a1f820d0154a.png">

**@antoinemacia:** How many times were you taken by surprise by an unexpected outcome of something you had visualised vividly? Is happy-path prioritisation a factor of cognitive ease?
**@mcgain:** Rarely surprised by "bad things" because he is a pessimist who does disaster planning. If something fails, he may be surprised that it failed in a way he didn't see coming. Do optimists think about the happy path instead?

**@antoinemacia:** The discussion of vivid imagery and how it sways our decision-making process is reminiscent of the priming discussion.

**@elle:** The descriptions of items on a restaurant menu can have a big effect on popularity (e.g. adding menu descriptions). At one restaurant, simply calling a poorly performing item "Summertime Corn" made it a big selling item

**@mcgain:** When someone produces a document—let's say an RFC—that is long, there is a temptation to think the author *must* have a deep understanding of the subject matter while another person submitting a 1-page document *must* not have thought through the topic. This is related to the vivid effect rather than the reality of the document yet it's easy to fall for.
**@lachlanhardy:** There are situations where it goes the other way; if you read a 1-page document that clearly outlines a discussion and then you receive a 10-page document on the same matter, you can think "could this really add more?" There is an anchoring effect.
There could be overlap with Amazon's 6-page pre-meeting memo. It creates an expectation that you right a minimum amount of detail without writing too much which can remove some bias.
**@elle:** And this is why your uni assignments have strict word-limits.

It was generally agreed that Adam has had his one big rant for the day.

**@mcgain:** "Money is keeping score"; it was important until that realisation. Because of this, money used to be a core value but that didn't align with the idea that "I don't care what people think of me". This also drove the question "why am I competing with my friends to make more money?".

**@antoinemacia:** Some people see money as a means to survival whereas the rest sees it as a proxy for points or achievement. When you come to the realisation that we spend much of our lives trying to avoid the emotional pressures that we put upon ourselves, you liberate yourself. The biggest lesson in these chapters is that the less you focus on money, the more you can avoid the effects mentioned in this book.

**@antoinemacia:** According to the Wikipedia page on regret, the greatest regret that most people have is that they have chosen the wrong path in education.

**Comment by lachlanhardy** [comment]
Superb notes, thanks!

**Comment by HashNotAdam** [comment]
@lachlanhardy, thank you for providing the pretty to break up the wall of text 😆
