### ISSUE TITLE
Thinking fast and slow: chapters 37-end: Tue 10th

### ISSUE THREAD

**Issue by mcgain** [Blackmill/book-club#56]
Aiming to read:
The rest of the book

MC: @mcgain 
Notes: @lachlanhardy

See you 12 pm Tuesday, Mar 10th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the Slack beforehand.

**Comment by lachlanhardy** [comment]
My limited notes:

## Chapter 37

We discussed the U-index. We found it fascinating, but feel like the information we've been given lacks detail.

Some people enjoy cooking on the weekend but not weekdays. There are reasons for that but what would they answer to the question of whether they enjoy cooking?

What are the childcare differences between the US and France that might account for the differing answers there? It might not be the women, but the support systems around them.

We discussed random sampling and how to get more representative results from employee happiness surveys.

We agree with the points about happiness depends what you pay attention to.

## Chapter 38

Mawige!

The ideas here seem outdated. Do women really do more housework after marriage? Or is more likely after moving in with a man?

## Conclusions

This section introduces more new ideas than we're keen on.

We were all fascinated by the condemnation of libertarianism and the descriptions of libertarian paternalism.

We had a long conversation of what the point of this book might be:
 - a summary of his life's work?
 - a justification of his ideas?
 
### Was it a good idea to read this book?

We all struggled with it at some point, but we each found useful things.

The repercussions on this book on political outlook are interesting. 

The two extremes are wrong and the right answer is somewhere in the middle but that's no fun.

We referenced the recent Freakonomics podcast on socialism: https://freakonomics.com/podcast/socialism/
