### ISSUE TITLE
A suggestion to start a slack channel

### ISSUE THREAD

**Issue by elle** [Blackmill/book-club#6]
I was thinking should we start a channel in a slack somewhere where we can communicate with everyone.

Can either invite you to our Slack? Alternatively, use RubyAU Slack?

I noticed that @cattekin and @nickspragg are not on RubyAU Slack...

cc @lachlanhardy @saramic @HashNotAdam @davich @SophieRoseMcDonald

**Comment by HashNotAdam** [comment]
Happy with any decision but, if it could go into RubyAU, that would save using more RAM.

**Comment by SophieRoseMcDonald** [comment]
Happy for a channel in ruby AU slack channel

**Comment by lachlanhardy** [comment]
Even with only 4-5 regular attendees, we already have people who aren't members of the Ruby Australia community, let alone the Ruby Australia Slack. I'll see what I can work out.

**Comment by HashNotAdam** [comment]
Fair enough—I did just get a shiny new 32GB machine 😆

**Comment by lachlanhardy** [comment]
Elle has invited folks to a channel in Blackmill Slack, we'll see how it goes.
