### ISSUE TITLE
Nudge: chapters 4, 5, & 6: July 14

### ISSUE THREAD

**Issue by tomdalling** [Blackmill/book-club#74]
Nudge: Improving Decisions About Health, Wealth, and Happiness
by Richard H. Thaler, Cass R. Sunstein

https://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness-ebook/dp/B00A5DCALY/

Aiming to read:

Chapter 4: When Do We Need a Nudge?
Chapter 5: Choice Architecture
Chapter 6: Save More Tomorrow

MC: @tomdalling 
Notes: @HashNotAdam
See you 12 pm Tuesday, July 14th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand

**Comment by HashNotAdam** [comment]
# Chapter 4: When do we need a nudge?

- Offer nudges that are most likely to help and least likely to inflict harm
- People will need nudges for decisions that are difficult and rare, for which they do not get prompt feedback, and when they have trouble translating aspects of the situation into terms that they can easily understand

## Fraught choices

- Predictable problems arise when people must make decisions that test their capacity for self-control
- With "investment goods" (e.g. exercise, flossing, dieting) costs are immediate but benefits are delayed
- "Sinful goods" (e.g. smoking, alcohol, doughnuts), on the other hand, give pleasure now and delayed consequences
- Both investment and sinful goods are prime candidates for nudges
- Nudging required is proportional to the difficultly of the problem and availability of support mechanisms
- People become better at decision making the more they encounter a type of problem
- Rare, difficult choices are good candidates for nudges
- Learning is most likely if people get immediate, clear feedback after each try
- It is particularly hard for people to make good decisions when they have trouble translating the choices they face into the experiences they will have

## Markets: a mixed verdict

- Most of the time, competition ensures that price serves as a good signal of quality
- Irrational consumers will not alter the market as long as they do not predominate
- In the case of extended warranties, the consumer can't (easily) work out that the cost of the warranty is greater than its value and so the market does not apply downward pressure on pricing
- If consumers have a less than fully rational belief, firms often have more incentive to cater to that belief than to eradicate it (e.g. airline flight insurance)

# Chapter 5: Choice architecture

- Stimulus response compatibility: you want the signal you receive (the stimulus) to be consistent with the desired action
- In simple tasks like naming the colour a word is written in, the automatic systems always win over the reflective ones
- If you indirectly influence the choices other people make, you are a choice architect

## Defaults: padding the path of least resistance

- If, for a given choice, there is a default option, we can expect a large number of people to end up with that option
- "Required choice" is where no options are selected by default and a choice is required. This can be valuable for emotionally charged issues
- Be careful using required choice as people will often consider it a nuisance and it is generally more appropriate for simple yes-or-no decisions

## Expect error

- Humans make mistakes
- A well-designed system expects its users to err and is as forgiving as possible (the Paris subway allows you to insert your ticket in any direction)
- A "postcompletion error" is the idea is that when you have finished your main task, you tend to forget things relating to previous steps (e.g. forgetting to put the cap back on a car petrol tank)
- A "forcing function" requires you to perform a task before you can get what you want (e.g. removing your bank card from the ATM before money is dispensed)
- "Drug compliance" is a major health care issue. Creating mediation with regular dosage (i.e. once per day) allows the Automatic System to take charge whereas less regular (i.e. every second day) is prone to failure

## Give feedback

- The best way to help Humans improve their performance is to provide feedback
- Well-designed systems tell people when they are doing well and when they are making mistakes
- Digital cameras include a fake "shutter click" when a picture is taken
- Feedback is only useful when used sparingly; excessive warnings are ignored

## Understanding "mappings": from choice to welfare

- When given options we are familiar with, it is easy for us to "map" the choice to an expected welfare outcome (i.e. vanilla or chocolate ice cream)
- When the choices are unfamiliar (i.e. cancer options) we are unlikely to be able to accurately make that mapping
- Often people have a problem in mapping products into money
- They propose governments regulate RECAP: Record, Evaluate, and Compare Alternative Prices.  Providers would be required to produce clear, simple summaries of usage data which could be used for comparisons

## Structure complex choices

- When we face a small number of well-understood alternatives, we tend to examine all the attributes and then make trade-offs
- When the choice set gets large, we must use alternative strategies, and these can get us into trouble
- As the choices become more numerous and/or vary on more dimensions, people are more likely to adopt simplifying strategies
- As alternatives become more numerous and more complex, choice architects are much more likely to influence choices
- Collaborative filtering shows you what people like you tend to like which can make you more comfortable in selecting products you don't know
- While collaborative filtering can be valuable, be warned that sometimes it's good to learn what people *un*like us like. Structuring choice sometimes means helping people to learn, so they can later make better choices on their own

## Incentives

- Libertarian paternalism does not eradicate market incentives and factors like supply and demand still need to be considered
- One way to think about incentives is to ask:
  - Who uses?
  - Who chooses?
  - Who pays?
  - Who profits?
- Free markets often solve for all key problems. Poor performers are driven from the market and good performers will be priced in accordance with people's tastes
- Sometimes incentive conflicts arise (e.g. the U.S. health care system, where physicians choose services and they are paid for by insurance)
- Good choice architects can take steps to direct people’s attention to incentives. A home thermostat showing cost per hour of lowering the temperature could be more effective than increasing the price of electricity

# Chapter 6: save more tomorrow

- People tend not to think about saving for retirement
- Two suggestions are offered: automatic enrollment in savings plans; and the Save More Tomorrow program
- Standard economic theory assumes people will calculate their retirement needs and save enough. This assumes people can calculate how much they need and that people have the willpower to implement the relevant plan
- In the United States, early pension plans were defined-benefit meaning they provide employer-funded benefits based factors such as salary and length of employment—this is detrimental for those who change job frequently
- New pension plans are likely to be defined-contribution plans. Benefits received by employees in retirement depend on the decisions they make about how much to save and how to invest

## Are people saving enough?

- Economists do not agree about how much saving is appropriate
- Most people in a defined-contribution savings plan say they should save more. While such a statement can be meaningless, it suggests they are open to a nudge

## Enrollment decisions: nudging people to join

- The first step in participating in a defined-contribution plan is to enrol
- These plans are highly-attractive yet 30% of eligible employees fail to enrol
- In the UK, some defined-benefit plans do not require employee contribution yet 49% do not sign up

## Making savings automatic

- An obvious answer is to default to automatic enrollment
- In one study, the opt-in method had 65% enrollment vs 98% for automatic enrollment
- Few people drop out of the automatically enrolled plans suggesting people are comfortable with the plan

## Forced choosing and more simplicity

- An alternative to automatic enrollment is required decision (e.g. pay is withheld until a decision is made)
- Providing a simple "yes" form with defaults (e.g. 2% savings rate and preselected asset allocation) also provides significant gains
- Adding many options will lower the participation rate

## Choosing contribution rates

- Typical automatic plans set savings at 2–3% with conservative investment choices; this rate is usually far too low
- One indication that people need help is they spend less than an hour determining their strategy, using simple shortcuts

## Education

- Education seems like an obvious way to help employees make better decisions but the evidence does not suggest that education is, in and of itself, an adequate solution
- After a seminar, employees tend to be excited about saving but don't follow through

## Save More Tomorrow

- Invites participants to commit themselves, in advance, to a series of contribution increases timed to coincide with pay raises
- Participants never see their take-home amounts go down, and they don’t view their increased retirement contributions as losses

## The role of the government

- The 2006 Pension Protection Act offers employers reduced regulation in exchange for implementing Save More Tomorrow and increasing employer contributions

**Comment by tomdalling** [comment]
dun
