### ISSUE TITLE
How to be an Antiracist: chapters 14–16: September 29th

### ISSUE THREAD

**Issue by pat** [Blackmill/book-club#86]
How to be an Antiracist by Ibram X. Kendi ([Amazon](https://www.amazon.com.au/How-Be-Antiracist-Ibram-Kendi/dp/0525509283), [Readings](https://www.readings.com.au/products/27328167/how-to-be-an-antiracist))

Aiming to read and discuss:

* Chapter 14: Gender
* Chapter 15: Sexuality
* Chapter 16: Failure

MC: @mcgain
Notes: John

See you 12 pm Tuesday, September 29th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by JohnTelfer** [comment]
14 Gender /15 Sexuality 
•	Intersectionality concept 
•	Racism in Queer spaces and Sexism in black spaces.
•	Lack of clarity around the solution and connection to antiracism.
•	Discussed exposing kids to multiculturalism and different family structures. 

16 Failure
•	Set context with historical evidence 
•	Conclusion of the book. Addresses the consequences to actions 
•	Defines protests and demonstrations. When people in power are sufferings then change happens. Policies will drive change not demonstration. 
•	Black live matter protests narrative. Law and order from the right and solidarity on the left. 
•	Protests provide Emotional support for people in these situations. 
•	Suasion, Black people misbehaving causes white people to be more racist. 
•	Incorrect conceptions of race routed in racism and hate are bound to fail.
•	Social currency of abolitionists. 
•	Policies that embed people with power and money. 
•	Self interest in how people react to policies, voters looking after themselves. Governments using fear to win votes. 
•	It’s hard to think we have all the tools for success.
