### ISSUE TITLE
Thinking in bets: first half of Chapter 6

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#93]
Book: Thinking in Bets by Annie Duke ([Amazon](https://www.amazon.com/Thinking-Bets-Making-Smarter-Decisions-ebook/dp/B074DG9LQF/), [Readings](https://www.readings.com.au/products/26565013/thinking-in-bets))

Aiming to read:
- the first half of Chapter 6: Adventures in Mental Time Travel
  - up to Ulysses contracts

MC: @lachlanhardy  
Notes: @HashNotAdam 

See you 12 pm Tuesday, Nov 17th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by lachlanhardy** [comment]
# Chapter 6
## Adventures in Mental Time Travel
### Let Marty McFly run into Marty McFly

> at the moment of the decision, accountability to our group can pop us briefly into the future to imagine the conversation about the decision we will have with that group.

-
>If we make a losing eating decision, like substituting SnackWell’s for apples, there’s no immediate outcome that lets us know there might have been a cost to that choice. If we repeat that kind of decision enough, there will be consequences, but they take time to play out.

-
>As with all the strategies in this book, we must recognize that no strategy can turn us into perfectly rational actors. In addition, we can make the best possible decisions and still not get the result we want. Improving decision quality is about increasing our chances of good outcomes, not guaranteeing them. Even when that effort makes a small difference—more rational thinking and fewer emotional decisions, translated into an increased probability of better outcomes—it can have a significant impact on how our lives turn out. Good results compound. Good processes become habits, and make possible future calibration and improvement.



### Night Jerry

>When we make in-the-moment decisions (and don’t ponder the past or future), we are more likely to be irrational and impulsive.

I'm uncomfortable with how the author raises issues like the military drawdown and lack of retirement funds as if the only reason for them is people not thinking of their future.

### Moving regret in front of our decisions

> That was one of the purposes of my loss limit in poker. Because of the loss-limit agreement I had made with myself and my group, I ran the conversation in my head that I’d be forced to have when I explained why I kept playing beyond my limit. It gave me a chance to regret the decision before I bought more chips.

-

> One of our time-travel goals is to create moments like that, where we can interrupt an in-the-moment decision and take some time to consider the decision from the perspective of our past and future.

-
>“Every 10-10-10 process starts with a question. . . . [W]hat are the consequences of each of my options in ten minutes? In ten months? In ten years?” – Suzy Welch

This kind of reminds me of a decision-making tool Elle and I used for a while. We used to carry a die each. We'd use it to determine the answer to those relatively insignificant decisions that are somehow hard: which film to watch, what to get for dinner, where to go, etc. Rolling the die gave us an answer. Which helped us know if we really wanted that result or not.

> Moving regret in front of a decision has numerous benefits. First, obviously, it can influence us to make a better decision. Second, it helps us treat ourselves (regardless of the actual decision) more compassionately after the fact. We can anticipate and prepare for negative outcomes. By planning ahead, we can devise a plan to respond to a negative outcome instead of just reacting to it. We can also familiarize ourselves with the likelihood of a negative outcome and how it will feel. Coming to peace with a bad outcome in advance will feel better than refusing to acknowledge it, facing it only after it has happened.

### The flat tire, the ticker, and a zoom lens
> We would do well to view our happiness through a wide-angle lens, striving for a long, sustaining upward trend in our happiness stock,

### Yeah, but what have you done for me lately?
> The way we field outcomes is path dependent. It doesn’t so much matter where we end up as how we got there.

-
>The zoom lens doesn’t just magnify, it distorts.

### Tilt
>when we are on tilt we aren’t decision fit.

I really enjoy the idea of identifying when we are 'decision fit'. What are other indicators that we're not decision fit?

The more strategies we raise in our decision group, the more we can reflect on and consider in moments away from that group. Accountability to the group makes this possible.

**Comment by HashNotAdam** [comment]
## Discussion

[@lachlanhardy](https://github.com/lachlanhardy): Really liked the idea that "your accountability to the group pops you into the future". If you know you will need to explain your decisions, in the moment, you will consider how you are going to justify your actions.

[@lachlanhardy](https://github.com/lachlanhardy): It is valuable to understand that no strategy can make us rational actors, they simply point us in the right direction. Improving decision quality is not about guaranteeing good outcomes, it's about increasing the chances of them.

[@mcgain](https://github.com/mcgain): Found that the metaphors obscured the lessons and was forced to re-read.

[@HashNotAdam](https://github.com/HashNotAdam): One challenge is that to receive maximum benefit, you will need your group to be diverse. The idea seems to work well when focusing on specifics (i.e. a group of poker experts discussing poker hands) but a more broad-based group could suffer from a lack of data from outside its bubble. This might be easier to deal with within the workplace than in private.
[@lachlanhardy](https://github.com/lachlanhardy): This could be the benefit of small business groups, CTO, or Men Championing Change meetups where a topic is set centrally, someone local gives a talk, and that creates questions that are discussed in groups.
[@mcgain](https://github.com/mcgain): Used to do this at Shopify every quarter. The engineering group would put topics on a whiteboard and then break into groups to discuss.

[@lachlanhardy](https://github.com/lachlanhardy): Spent a lot of time thinking about how to apply a poker-style loss limit to non-monetary life decisions but didn't come up with a good answer.
[@HashNotAdam](https://github.com/HashNotAdam): Possibly, in the case of allocating time for someone to work on an out-of-the-box idea, maybe the amount of time you allow is relative to the potential ROI. If you can't "spike" it within that time period, the idea is deemed too risky.
[@lachlanhardy](https://github.com/lachlanhardy): In the case of something like trialling Basecamp's Shape Up process, each cycle is about 2 months. How do you work out how many cycles you need to try? In Shape Up, it is said that it will take 6 cycles for the objectives and key results (OKRs) to begin to feel useful. If you check your OKRs quarterly, that's 18 months.

[@lachlanhardy](https://github.com/lachlanhardy): Enjoyed the 10-10-10 idea and how the author inverted the idea from "how will I feel in 10-minutes, 10-months, or 10-years" to "how would I feel now if had made that decision 10-minutes, 10-months, or 10-years ago".
[@lachlanhardy](https://github.com/lachlanhardy): Used to carry a die to help make decisions. If you can't choose what type of food to eat, rolling the die forces a choice. The idea, however, isn't to abide by the die, it is that the die making a decision forces you to think into the future and consider if you will really want that choice or if you even really care what the choice is.

[@lachlanhardy](https://github.com/lachlanhardy): Found the idea that, if something bad happens to you, it is easy to get caught up in the moment and think life is terrible even if something great happened to you just the day prior (i.e. a promotion at work).
[@elle](https://github.com/elle): Research shows that a raise/promotion at work gives you about a week of pleasure and then you adapt to the new circumstances and the joy disappears.

[@lachlanhardy](https://github.com/lachlanhardy): Interesting that the path to getting to an outcome feels more important than the outcome. Even if the result is good, you can feel bad about it if the journey was tough. This is opposed to the idea that "the end justifies the means"
[@elle](https://github.com/elle): You can die any day so live in the moment

[@lachlanhardy](https://github.com/lachlanhardy): When people are "on tilt", they are not decision-ready. Are there other circumstances in life where we can say "I am not fit to make a decision"?
[@elle](https://github.com/elle): When making a decision to buy something expensive, it can be beneficial to place at least a day (if not a week) between the idea and the decision. If after the period, you still want to buy, then it's more likely to be the right choice.
[@mcgain](https://github.com/mcgain): Reminds of the lay-by days where friends would be locked into a purchase that, by the time they've paid it off, [@mcgain](https://github.com/mcgain) had forgotten he ever wanted it. The new BNPL platforms now let you have the product immediately and so it hurts the ability to consider if you actually want that item.
