### ISSUE TITLE
Sand Talk: January 5th

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#97]
New book: [Sand Talk](https://www.textpublishing.com.au/books/sand-talk) by Tyson Yunkaporta ([Amazon](https://www.amazon.com/dp/0062975641/), [Readings](https://www.readings.com.au/products/27439470/sand-talk-how-indigenous-thinking-can-save-the-world))
> This remarkable book is about everything from echidnas to evolution, cosmology to cooking, sex and science and spirits to Schrödinger’s cat.
> Tyson Yunkaporta looks at global systems from an Indigenous perspective. He asks how contemporary life diverges from the pattern of creation. How does this affect us? How can we do things differently?
>Sand Talk provides a template for living. It’s about how lines and symbols and shapes can help us make sense of the world. It’s about how we learn and how we remember. It’s about talking to everybody and listening carefully. It’s about finding different ways to look at things.
>Most of all it’s about Indigenous thinking, and how it can save the world.

We've found our discussions in this book are super chunky so only doing one chapter/section per session.

Aiming to read:
- First Law

MC: @HashNotAdam  
Notes: @mcgain 

See you 12 pm Tuesday, January 5th @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by mcgain** [comment]
Notes

Adam - “This chapter does my head in”

### Wibbly wobbly, timey wimey stuff

Do indigenous people have a fundamentally different way of seeing the world? Or do they just use different words?

Yunkaporta’s argument seems to make logical sense to Lachlan, but are hard to accept.

Adam never managed to gain an appreciation of the concept of a singularity of time and space. He couldn’t figure out the connection between the non-linear time and the other concepts in this chapter. Why does time have to be non-linear to support things? 

Everyone agreed, or at least, offered no enlightening statements

Michael read most of the book sitting next to a river with nothing to do. It gave him a new appreciation for the book. It resonated more in the bush. “There is no linear time in the bush”

Adam thinks we should be reading this book like people read the bible. Try to understand the meaning behind the words, not necessarily the literal words themselves.

Lachlan tried to figure out the practical implications for women (and the author only mentions women) working in the three life cycle of child, mother and grandmother. He struggled to figure out the point of this system. Possibly from carers point of view, where the young look after the elderly? 

Adam isn’t going to buy this theory any time soon, but he can appreciate the connectedness that the theory must create. Abrahamic churches evolved to build community ties, does this do the same thing?

Michael is an experienced map-reader and always apys attention to the cardinal directions to the point where he has internalised it. In the northern hemisphere, his internalisation doesn’t work and so he’s discombobulated. Have we internalised the concept of linear time so much that we can’t see out of it?

Lachan knows people who have internalised tactical positioning and assault tactics. They’ve internalised that theory, much as we all have internalised how to intuitively use technology. 

Adam asks what“Tangible reality only exists in defiance of linear time” means?

Lachlan thinks it relates to the authors rejection of objectivity. Using certain language to define things shapes those things, just like observing a particle (schrodinger’s cat) changes that particle. 

Adam thinks that the author is being very close minded about criticising the close-mindedness of second person science.
It’s annoying that Yunkaporta doesn’t present his views to the physicist he’s talking to. We would really like to hear the physicist’s response to his musings. 

Adam can’t really comprehend the link between the particles and linear time. Pat and Lachlan make some attempts at explaining it. In real time we can’t know where the particle is, until you see it. The uncertainty principle is at play here. The possible positions form a field of probabilities.

Linear time is stopping us thinking about physics properly, Michael says, but how this helps his argument about closed vs open systems is unclear. 

Richard provides an example of a physics experiment (https://bigthink.com/surprising-science/particle-time-travel)  where a particle arrived somewhere before it departed elsewhere. Perhaps thinking about time in a non-linear way could help with understanding of physics.

Lachlan talks about the difference between good and bad, and people who do good and bad things. No one is “evil” but we can use the term to describe people who on the whole, do evil things. Even then, that person is not completely bad.

Yunkaporta changes tone a lot, from formal to informal, from academic to colloquial. We have said previously that we like this style, but here he switches from snark and rage to positivity. Adam found this annoying.

“Egos always get in the way of a good yarn”

Adam thinks he went off the rails a bit with “Schrodinger’s cat doesn’t help us with family stability in a financial crisis”, but he did enjoy the story of the girls who chased the moon, thinking it was a fish. Although the story remains unelaborated, Adam thinks plenty of good philosophical and moral teachings could come out of it.

### Sustainable Cities

Adam asks, are cities redeemable?

Pat doesn’t really like the definition of civilisation given, and doesn’t exactly have an answer for Adam, but admits this raised some great questions around sustainability. 

Lachlan points out a series of programmes that could make a sustainable city out of Melbourne in 10 years. He also read a scifi novel that had similar concepts.(https://www.normalise.it/) (https://www.goodreads.com/book/show/45872179-savage-legion)

What do cities actually produce? Money? Static heaps? Ideas? Is this enough? 

Richard asked do widely distributed static heaps (ie. Everyone moving to the country) actually help here?

Lachlan thinks that it’s easier to renew and fix those widely distributed people, than fixing a city. He mentions the energy of a curve. Once you get to certain economies of scale, our energy usage can go down. Unfortunately, the peak of the curve is higher than the earth can sustain. The doughnut economic model is a way to think about this (https://en.wikipedia.org/wiki/Doughnut_(economic_model)) 

Richard thinks Yunkaporta actually means to go further and that we should all just go live off the land. Different value systems value different things.

In a podcast, Yunkaporta said life would be better if there were no internet at all. That said, he doesn’t eschew technology completely. 
Adam asks if Yunkaporta thinks that life for indigenous people would be better if the west had never arrived. Richard says this is certainly the case, given the loss of life an culture they’ve experienced.

Pat says this book is more about introducing new concepts and ways of thinking about things.

Richard says the book is succeeding if that is the point.

Lachlan says that this book introduces new words and meanings that are helpful. The book is sticking in his mind.

Michael says that all civilizations are doomed, as per Aristotle’s Telos principle.  Cities will be bound to fail, so maybe going back to the way indigenous cultures did things is the next big thing.

Lachlan says maybe not all civilisations fail. Indigenous cultures survived 78,000 years, so maybe ours will not fail if we do the right things.
